### ISSUE TITLE
用法：如何消除显示的 [S.1. : s.n.]

### ISSUE THREAD

**Issue by PkuRainBow** [hushidong/biblatex-gb7714-2015#105]
如图所示

![image](https://user-images.githubusercontent.com/4639578/140618053-79c7da36-492f-4da9-a00b-7f39edd03016.png)

**Comment by hushidong** [comment]
加上 gbpub=false选项。
比如：
```
\usepackge[style=gb7714-2015ay,gbpub=false]{biblatex}
```

**Comment by PkuRainBow** [comment]
Great, problem is solved!
