### ISSUE TITLE
如何在Reference中显示所有作者（而非et al.）以及把年份放到会议名后面？

### ISSUE THREAD

**Issue by PkuRainBow** [hushidong/biblatex-gb7714-2015#106]
您好，

我这边已经参考https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E4%BF%AE%E6%94%B9%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E9%BB%98%E8%AE%A4%E6%8E%92%E7%89%88%E8%A1%8C%E4%B8%BA 做了修改，已经采用biblatex/biblatex-gb7714-2015 的情况下，

(1)  编译后还是只显示4个作者，多余四个就是显示et.al, 请问如何强制显示所有作者？

(2)  另外请问如何把年份显示到会议名字后面？

![image](https://user-images.githubusercontent.com/4639578/140631194-b11e3a0d-d98c-4f9e-bf24-e68471d4ea13.png)

**Comment by hushidong** [comment]
```

\documentclass{ctexart}
\usepackage[style=gb7714-2015ay,gbnamefmt=lowercase,gbpub=false,maxbibnames=99,mergedate=none]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Inproceedings{ref-replace-char,
  Title                    = {Cognitive Radio and Cooperative Strategies for Power Saving in Multi-Standard Wireless Devices},
  Address                  = {Florence, Italy},
  Author                   = {Rodriguez, J. and P. Marques and A. Radwan and K. Moessner and R. Tafazolli and others},
  Booktitle                = {Future  Network Mobile Summit (FNMS)},
  Date                     = {2010-06}
}

\end{filecontents}

\addbibresource{\jobname.bib}


\begin{document}

\nocite{*}

\printbibliography

\end{document}

```

结果：
![图片](https://user-images.githubusercontent.com/20421795/140632613-ce69e995-ed6c-46f9-94b4-3f2ee74c75ba.png)

**Comment by PkuRainBow** [comment]
Thanks!
