### ISSUE TITLE
中文参考文献的作者分隔符设置问题

### ISSUE THREAD

**Issue by ikroal** [hushidong/biblatex-gb7714-2015#107]
您好，
我在撰写论文的时候发现这个包为中英文参考文献设置了不同的作者分隔符。对于中文参考文献，默认的作者分隔符是中文的逗号。对于英文的参考文献，默认的作者分隔符是英文的逗号加上空格。现在我想将中文参考文献的作者分隔符设置为与英文一致，请问有什么可行的办法吗？

下图是目前的效果：
![image](https://user-images.githubusercontent.com/11755265/141318838-a54208e2-f63c-4bbb-8f6b-63232ca2a482.png)
我已经尝试查找过issue，并设置过全局的作者间隔符，即以下命令：
\DeclareDelimFormat{multinamedelim}{, }
\DeclareDelimFormat{finalnamedelim}{, }
然而，该命令只会影响英文的参考文献，却不会对中文参考文献生效。

**Comment by hushidong** [comment]
最好能给一个mwe。
你这个问题通常是不会发生的，因为默认都是英文标点，你现在出现这种情况最可能的是你的模板做了设置。

**Comment by hushidong** [comment]
\DeclareDelimFormat*{multinamedelim}{\iffieldequalstr{userd}{chinese}{, }{，}}%\addcomma\addspace

**Comment by hushidong** [comment]
改成这样试试

**Comment by ikroal** [comment]
> 最好能给一个mwe。 你这个问题通常是不会发生的，因为默认都是英文标点，你现在出现这种情况最可能的是你的模板做了设置。

谢谢解答，我发现是我自己的问题，已经解决了😰

顺便说下我的问题，以便后来人排查：我在引入中文参考文献时，将作者之间的and替换为了`，`。所以导致默认的分隔符失效了。然而，由于显示上是正常的，所以没有发现这点。
例如：
```
@article{zhangchengbo,
  title={面向分布式图计算作业的容错技术研究综述},
  author={张程博，李影，贾统},
  journal={软件学报},
  volume={32},
  number={7},
  pages={2078--2102},
  year={2021}
}
```
