### ISSUE TITLE
会议和期刊分隔符的不同

### ISSUE THREAD

**Issue by Lyanf** [hushidong/biblatex-gb7714-2015#110]
学长您好，我注意到会议文章，即[C]类型的时候，目前输出的是
```
Lin T Y, Dollár P, Girshick R, et al. Feature pyramid networks for object detec-
tion[C]//Proceedings of the IEEE conference on computer vision and pattern
recognition. 2017:2117-2125.
```
而期刊文章，即[J]类型的时候，输出的是
```
RenS,HeK,GirshickR,etal.Fasterr-cnn:Towardsreal-timeobjectdetectionwith
region proposal networks[J]. Advances in neural information processing systems,
2015, 28:91-99.
```
在文章名和期刊名之间的分隔符，分别是`//`和`.`
想问一下，有没有方法把会议文章的分隔符改成`.`呢，因为学校（sjtu）这边给的示例是用的`.`，用`//`的感觉有点儿怪怪的。

感谢~

**Comment by hushidong** [comment]
改当然是可以的，但这是国标要求呀，可以按自己的兴趣改么？

改的方法如下：

```
\documentclass{ctexart}
\usepackage[paperheight=16cm]{geometry}
\usepackage[style=gb7714-2015,gbpunctin=false]{biblatex}
\usepackage[colorlinks]{hyperref}
\DefineBibliographyStrings{english}{in={\adddot\space}}
\DefineBibliographyStrings{english}{incn={\adddot\space}}


\begin{filecontents}{\jobname.bib}
@InProceedings{王临慧2010-138,
  author    = {王临慧},
  title     = {从几组声母的演变看天津方言形成的自然条件和历史条件},
  bookauthor= {曹志耘},
  booktitle = {汉语方言的地理语言学研究：首届中国地理语言学国际学术研讨会论文集},
  year      = {2010},
  publisher = {北京语言大学出版社},
  pages     = {138},
  address   = {北京},
}

@Proceedings{牛志明2012--,
  title     = {综合湿地管理国际研讨会论文集},
  year      = {2012},
  editor    = {牛志明 and 斯温兰德 and 雷光春},
  publisher = {海洋出版社},
  address   = {北京},
}

\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}
\printbibliography
\end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/147758874-689ae2ed-43e0-4b2b-b5db-6d863910d66e.png)

**Comment by Lyanf** [comment]
感谢学长的及时回复~

这个东西我也很纠结，因为今年上交突然官方给了个latex模板，做的很差，几乎不能直接用，而且和往年大家一直用的那个民间的模板差异挺大的。

官方模板里面的参考文献是直接硬写的，没有用bib文件，且示例里面用的`.`，交大也没说自己用的是不是国标，老师还专门发了参考文献的示例邮件，主要就差在这个分隔符上了，我现在就怕被说格式出错，尽量在原来民间模板的基础上往他的示例去靠，贼难受。

**Comment by hushidong** [comment]
我记得sjtug模板那边的帖子说过，好像交大在去模板化，用这个sjtug应该是没问题的。当然你要根据实际情况处理。文献这块biblatex提供了任何的修改可能性，只需要明确要求就能实现的。你如果有需要可以像这里一样提出来。

**Comment by hushidong** [comment]
我记得sjtug模板那边的帖子说过，好像交大在去模板化，用sjtug那个模板应该是没问题的。当然你要根据实际具体情况处理。文献这块biblatex提供了任何的修改可能性，只需要明确要求就能实现的。你如果有需要可以像这里一样提出来。

**Comment by Lyanf** [comment]
> 我记得sjtug模板那边的帖子说过，好像交大在去模板化，用sjtug那个模板应该是没问题的。当然你要根据实际具体情况处理。文献这块biblatex提供了任何的修改可能性，只需要明确要求就能实现的。你如果有需要可以像这里一样提出来。

感谢学长回复，你真的好懂hhhh，那个帖子我也看到了，但是我昨天给学位办打电话，他说封面啥的还是要和模板一样，然后具体哪些可以不一样，让今天我再打电话问负责的老师，所以到底是不是真的要去模板化我也很懵逼，而且那个去模板化是在官方模板出来之前的回复，民间模板开发的大佬觉得官方模板太丑，就不想改了，我现在就很慌。。

然后就是学院这边看到学校给了模板，他要求按照那个模板来（即使学校没要求），我今天也打算再问问学院的老师，能不能用民间的（毕竟官方的基本上用不了）。

再次感谢学长的帮助~

**Comment by Ynjxsjmh** [comment]
我也有这个疑惑，根据的章节“附录A 顺序编码制参考文献表著录格式示例”里的描述，`C` 代表会议录，而会议录的格式是没有 `//` 的

![image](https://user-images.githubusercontent.com/40143136/217450154-a75863a6-d896-41a4-937e-dd75384e1c06.png)

![image](https://user-images.githubusercontent.com/40143136/217449566-aef442dc-934b-4e5a-b3b0-fda58bff246f.png)

有 `//` 的我注意到的是“专著中析出的文献”

![image](https://user-images.githubusercontent.com/40143136/217449763-66b1cc39-3577-4a08-8aeb-c31d7c6cf090.png)

但是“专著中析出的文献”中文献类型标识却也有 C，有点搞不清楚是怎么判断的。

**Comment by hushidong** [comment]
后面这个是会议论文，是论文集中析出的，所以有。

**Comment by Ynjxsjmh** [comment]
@hushidong 感谢回复，所以说文献类型标识代码 C 的含义在书中其实并不准确，它其实可以指会议录，也可以指会议录中的一篇会议论文。当它指会议录时采用的格式是 `[C]. `，当它指会议录中的一篇会议论文时采用的格式是 `[C]//`。

**Comment by hushidong** [comment]
是的。

**Comment by zepinglee** [comment]
> @hushidong 感谢回复，所以说文献类型标识代码 C 的含义在书中表格其实并不准确，它其实可以指会议录，也可以指会议录中的一篇会议论文。当它指会议录时采用的格式是 `[C]. `，当它指会议录中的一篇会议论文时采用的格式是 `[C]//`。

第 4 节的 6 种格式和附录 B.1 的 16 种类型标识是两套相关性不太强的系统。“//” 可以理解为“in:”。
