### ISSUE TITLE
希望支持entrysubtype域

### ISSUE THREAD

**Issue by YP-Li** [hushidong/biblatex-gb7714-2015#113]
biblatex支持entrysubtype域，例如报纸文章，entrytype=article，entrysubtype=newspaper。

-----
现在的版本中采用note域来判断专利和报纸。
zotero可以自动导出note域中的笔记，但是当note中含有回车时，.bib文件会出现故障，因此用note域表示newspaper等并不方便。
-----

**Comment by hushidong** [comment]
你这个提议很好，我之前也发现note域尽管作用不大，但在很多网站输出中是存在一定的信息的，也就是有一定作用的，但没有强的动力来改。你提出用entrysubtype域来表示，这是很好的，我当时没有注意到，感谢提醒。

另外，由于我没有用zotero，所以请问一下，在zotero中entrysubtype域的设置，也是需要手动设置的吧？

**Comment by hushidong** [comment]
你这个需求很快实现，后面更新到ctan上去。

**Comment by hushidong** [comment]
已经可以了，ctan已上传，等公告后就可以更新了。

**Comment by hushidong** [comment]
示例
```
\documentclass{ctexart}

\usepackage[style=gb7714-2015]{biblatex}

\begin{filecontents}{\jobname.bib}
@Newspaper{余建斌2013--,
  author  = {余建斌},
  date    = {2013-01-12},
  journal = {人民日报},
  number  = {2},
  title   = {我们的科技一直在追赶: 访中国工程院院长周济},
  url     = {http://paper.people.com.cn/rmrb/html/2013-01/12/nw.D110000renmrb_20130112_5-02.htm},
  urldate = {2013-03-20},
  year    = {2013},
}

@Article{丁文祥2000--,
  Title                    = {数字革命与竞争国际化},
  Author                   = {丁文祥},
  Date                     = {2000-11-20},
  Journaltitle             = {中国青年报},
  Number                   = {15},
  Note                     = {News}
}

@Article{张田勤2000--,
  Title                    = {犯罪DNA库与生命伦理学计划},
  Author                   = {张田勤},
  Date                     = {2000-11-12},
  Journaltitle             = {大众科技报},
  Note                     = {Newspaper},
  Number                   = {7}
}

@Article{傅刚2000--,
  Title                    = {大风沙过后的思考},
  Author                   = {傅刚 and 赵承 and 李佳路},
  Date                     = {2000-04-12},
  Journaltitle             = {北京青年报},
  entrysubtype             = {Newspaper},
  Url                      = {http://www.bjyouth.com.cn/Bqb/20000412/GB/4216%5ED0412B1401.htm},
  Number                   = {14},
  Urldate                  = {2005-09-28}
}

@Book{全国广播电视标准化技术委员会2007-1-1,
  Title                    = {广播电视音像资料编目规范:第2部分~ 广播资料:GY/T202.2-2007},
  Address                  = {北京},
  Author                   = {全国广播电视标准化技术委员会},
  Note                     = {standard},
  Pages                    = {1},
  Publisher                = {国家广播电影电视局广播电视规划院},
  Year                     = {2007}
}

@Book{全国信息文献标准化技术委员会2010-3-3,
  Title                    = {文献著录:第4部分~ 非书资料:GB/T3792.4-2009},
  Address                  = {北京},
  Author                   = {全国信息文献标准化技术委员会},
  entrysubtype             = {Standard},
  Pages                    = {3},
  Publisher                = {中国标准出版社},
  Year                     = {2010}
}

@Standard{全国信息与文献标准化技术委员会2010-2-3,
  author    = {全国信息与文献标准化技术委员会},
  title     = {信息与文献\ \ \ \ 都柏林核心元数据元素集: GB/T 25100—2010},
  year      = {2010},
  address   = {北京},
  pages     = {2--3},
  publisher = {中国标准出版社},
}



\end{filecontents}

\addbibresource{\jobname.bib}



\begin{document}

\nocite{*}

\sloppy
\printbibliography

\end{document} 
```

结果为：

![图片](https://user-images.githubusercontent.com/20421795/150913058-1dea653a-2d7a-4e65-b012-3f4f2dbda815.png)

**Comment by YP-Li** [comment]
@hushidong 最近一直在紧张忙碌地撰写博士毕业论文，没有及时处理github上的信息，非常抱歉。
看到了你的更新，非常感谢！

## 1. 有关zotero及文献导出

我现在使用的是开源文献管理器[zotero](https://www.zotero.org/)，zotero生态下有一个自动导出bib文件的开源插件[Better BibTeX](https://retorque.re/zotero-better-bibtex/)，该插件可以自动、实时导出格式较为规范的bib文件，从而实现与latex工程的完美衔接，免去了手动生成bib文件的麻烦。这套文献管理方式在我周围的博士群体里有不少人采用。


Better BibTeX的bib导出功能不需要复杂的设置（也没有提供相应的前端设置功能），它提供了不同的文献导出模式，其中，在Better BibLaTex导出模式下，`报纸`类文献会自动添加`entrysubtype = {newspaper}`，例如：
```
@article{Huo21,
  title = {专访丁仲礼：实现``碳中和''需以市场机制为基础，技术迭代为前提},
  author = {霍, 思伊},
  date = {2021-06-08},
  journaltitle = {中国新闻周刊},
  location = {{北京}},
  url = {http://www.inewsweek.cn/finance/2021-06-08/12806.shtml},
  urldate = {2022-01-14},
  entrysubtype = {newspaper}
}
```

## 2. 有关`entrysubtype`域的调研

当我使用`biblatex-gb7714-2015`包无法自动显示为`[N]`时，我去查找原因。在我发现上述bib文件中有`entrysubtype`后，查阅了biblatex相关技术文档（现在已经不知道是哪个文档了，当时非常着急），文档显示，`entrysubtype`是为了更精细化地管理文献类型准备的。其中一个印象比较深刻的例子是`报纸`类。

然后我拜读了本库的说明文档，发现对`报纸`类型的支持方式并未与上述方式保持一致，是使用了`note`域。所以才提出这个issue。

## 3.不支持`entrysubtype`时的临时解决方案

在发现上述问题后，我采取了临时的解决方案，即：我分成两个bib文件，第一个是手写的，将我论文里引用的报纸类文献集中在这个bib中，并手动添加`note={news}`，第二个是zotero自动导出的，我的所有文献，包括报纸类文献。

在tex文件中，先\addbibresource{第一个.bib}，再\addbibresource{第二个.bib}，就能达到`报纸`正确显示的目的。

----

由于我不会手动更新latex宏包，所以无法体验到你的上述版本升级，但是非常感谢你高效的回复和处理，我会在下一个MikTex或LiveTex中享受到这一变化。再次感谢你的贡献，在我的博士论文中帮了大忙！

**Comment by hushidong** [comment]
感谢你提供了一个很好的思路，就需要你这种认真研究，敢于提出新想法的精神。这些年我一直没有发现用 entrysubtype，包括我和文博翻译biblatex手册的时候也没有注意到，无论是否因为用的少等等因素。若没有你这一提醒，显然不会有现在更好的改进。非常感谢！！

至于更新，有一个很简单的方法就是从这个库里下注bbx,cbx文件覆盖你系统内的文件即可，搜索一下系统中文件，就能找打文件位置所在。 

你说的没有更新时候的解决方法也很好，其原理是，后面加载的bib文件，相同entrykey的条目，后面的会覆盖前面的。
