### ISSUE TITLE
中文文献标题中含有空格时，空格会被“吃掉”

### ISSUE THREAD

**Issue by YP-Li** [hushidong/biblatex-gb7714-2015#116]
## 问题描述

bib文件中，**中文**文献标题有空格时，在编译后的参考文献中，标题的空格消失，需要手动在bib文件标题中打`\ `或者`\quad`强制显示空格。英文文献没事。

## 测试样例

[新闻](http://jingji.cntv.cn/2014/04/08/ARTI1396917452530649.shtml)的标题为`直购电试点输配电价获批 云南率先探索电价市场化`，在`获批`和`云南`之间有空格。

### (1) 在标题中包含空格

```
@article{14YunnanNeimeng,
  title = {直购电试点输配电价获批 云南率先探索电价市场化},
  year = {2014},
  month = apr,
  journal = {中国证券报},
  address = {{北京}},
  url = {http://jingji.cntv.cn/2014/04/08/ARTI1396917452530649.shtml},
  urldate = {2022-01-14},
  note={news}
}
```

编译结果中无空格：

![image](https://user-images.githubusercontent.com/39263931/156917235-15fbd533-9781-4a38-ad7c-100fd2da5153.png)

### (2) 在标题中包含`\空格`

```
@article{14YunnanNeimeng,
  title = {直购电试点输配电价获批\ 云南率先探索电价市场化},
  year = {2014},
  month = apr,
  journal = {中国证券报},
  address = {{北京}},
  url = {http://jingji.cntv.cn/2014/04/08/ARTI1396917452530649.shtml},
  urldate = {2022-01-14},
  note={news}
}
```

编译结果显示正确：

![image](https://user-images.githubusercontent.com/39263931/156917092-c968846d-7894-4728-a39b-6e2d4faed485.png)

**Comment by hushidong** [comment]
这个是正常的，跟正文中一样，两个CJK字符之间的空格会消掉
