### ISSUE TITLE
edition 为非数字时报错 Missing number, treated as zero.

### ISSUE THREAD

**Issue by zepinglee** [hushidong/biblatex-gb7714-2015#121]
```
Package: biblatex 2022/02/02 v3.17 programmable bibliographies (PK/MW)
File: gb7714-2015.bbx 2022/03/07 v1.1ebiblatex bibliography style
```

这是国标的一个例子。
<img width="410" alt="Screen Shot 2022-03-09 at 20 27 23" src="https://user-images.githubusercontent.com/12290822/157441792-7f4cdb2e-d118-4b9d-add7-06a8ad9aad68.png">

```tex
\documentclass{ctexart}
% \usepackage[style=numeric]{biblatex}
\usepackage[style=gb7714-2015]{biblatex}
\addbibresource{\jobname.bib}
\begin{filecontents}{\jobname.bib}
@book{4.1.2:7,
  author     = {王夫之},
  title      = {宋论},
  edition    = {刻本},
  address    = {金陵},
  publisher  = {湘乡曾国荃},
  date       = {1865(清同治四年)},
}
\end{filecontents}
\begin{document}
\cite{4.1.2:7}
\printbibliography
\end{document}
```

报错：
```
./main.tex:18: Missing number, treated as zero.
<to be read again> 
                   刻
l.18 \end
         {document}
```

**Comment by hushidong** [comment]
问题集中爆发啦。主要近期没有全面测试。特别是修改的时候，可能考虑现在的需求，忘记了之前的实现逻辑的目的了。
先在github更新，周末再更新ctan吧，太频繁了。这是一个问题，还简单一点，后面还有一个没有作者时的标点问题，要解决，可能比较麻烦。

**Comment by zepinglee** [comment]
你可可以考虑像 biblatex 一样添加 l3build 的测试，比如 <https://github.com/plk/biblatex/tree/dev/testfiles/pdftex>。其实我是子啊 thuthesis 的单元测试中发现的 <https://github.com/tuna/thuthesis/runs/5477020941?check_suite_focus=true>。
