### ISSUE TITLE
Chinese-erj textcite 引用同一个作者多篇文献时应该改成 author (year1; year2)，而不是 author (year1)、author (year2)

### ISSUE THREAD

**Issue by skymagician** [hushidong/biblatex-gb7714-2015#122]

**Comment by hushidong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你加个选项 sortcites=true

**Comment by skymagician** [comment]
> 
试了一下并没有起作用。
我在chinese-erj.cls里是这样写的

`%
% modified by hzz 20191009
% 1.为避免正文中出现因姓名歧义处理而引出的名的缩写使用uniquename=false选项
% 2.不再使用natbib选项，因为gb7714-2015ay样式已经定义了citet和citep命令
\usepackage[backend=biber,style=chinese-erj,uniquename=false,sortcites=true]{biblatex}
\renewcommand*{\bibfont}{\scriptsize}
\setlength\bibitemsep{0.2\baselineskip}
\renewcommand{\refname}{\small  参考文献}
\renewcommand{\parencite}{\cite} % if biblatex-gb7714-2015 更新则删除

\newcommand{\erjref}{
\vspace*{0.8\baselineskip}
\begin{flushleft}
\small 参考文献
\vspace*{-0.3\baselineskip}
\end{flushleft}}`

**Comment by hushidong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，我先看看，你可以做点其它事情。
    
        
            
        
    
    
        
        

        
    

    在2022年3月31日 ***@***.***> 写道： 








试了一下并没有起作用。

我在chinese-erj.cls里是这样写的

`%

% modified by hzz 20191009

% 1.为避免正文中出现因姓名歧义处理而引出的名的缩写使用uniquename=false选项

% 2.不再使用natbib选项，因为gb7714-2015ay样式已经定义了citet和citep命令

\usepackage[backend=biber,style=chinese-erj,uniquename=false,sortcites=true]{biblatex}

\renewcommand*{\bibfont}{\scriptsize}

\setlength\bibitemsep{0.2\baselineskip}

\renewcommand{\refname}{\small  参考文献}

\renewcommand{\parencite}{\cite} % if biblatex-gb7714-2015 更新则删除

\newcommand{\erjref}{

\vspace*{0.8\baselineskip}

\begin{flushleft}

\small 参考文献

\vspace*{-0.3\baselineskip}

\end{flushleft}}`

**Comment by hushidong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    ```\documentclass[twoside]{article}
    \usepackage{ctex}
    \usepackage{xcolor}
    \usepackage{toolbox}
    \usepackage[colorlinks]{hyperref}
    \usepackage{lipsum}
    \usepackage[top=3cm,bottom=3cm,left=3cm,right=3cm]{geometry}\usepackage[backend=biber,style=chinese-erj]{biblatex} ***@***.***{方军雄2007所有制,
  AUTHOR = {方军雄},
  DATE = {2007},
  JOURNALTITLE = {经济研究},
  PAGES = {82--92},
  TITLE = {所有制, 制度环境与信贷资金配置},
  VOLUME = {12},
 ***@***.***{方军雄2008,
  AUTHOR = {方军雄},
  DATE = {2008},
  JOURNALTITLE = {经济研究},
  PAGES = {82--92},
  TITLE = {所有制, 制度环境与信贷资金配置},
  VOLUME = {12},
  key={fang1}}\end{filecontents}
    \addbibresource{\jobname.bib}
    %
    \begin{document}
    \section{经济研究参考文献格式示例}\cite{方军雄2007所有制,方军雄2008}\parencite{方军雄2007所有制,方军雄2008}\textcite{方军雄2007所有制,方军雄2008}\citep{方军雄2007所有制,方军雄2008}\citet{方军雄2007所有制,方军雄2008}
    \printbibliography
    \end{document}```结果为：Message ID: ***@***.***>



    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }

**Comment by skymagician** [comment]
我找到问题了，是我的bib文件里的作者姓名略有不同（其中一个作者带有缩写）导致的，改完之后就正常了。谢谢！
