### ISSUE TITLE
译者只有一个的时候译者名和“译”之间出现了一个逗号

### ISSUE THREAD

**Issue by xkwxdyy** [hushidong/biblatex-gb7714-2015#126]
```latex
\documentclass{ctexart}
\usepackage[
  backend = biber,
  style = gb7714-2015
]{biblatex}

\begin{filecontents}{test.bib}
  @book{鲍里奇2002有效教学方法,
    title={有效教学方法},
    author={{加里·D·鲍里奇}},
    translator= {易东平},
    location= {南京},
    publisher= {江苏教育出版社},
    year={2002}
  }
}
\end{filecontents}
\addbibresource{test.bib}

\begin{document}
\cite{鲍里奇2002有效教学方法}

\printbibliography

\end{document}
```
![image](https://user-images.githubusercontent.com/87134063/163419321-fecb3dfc-d770-48de-818c-e37614c72e21.png)

mactex, 2022, 刚刚 更新完宏包（2022-0414-23:00）

**Comment by zepinglee** [comment]
<img width="752" alt="Screen Shot 2022-04-14 at 23 28 38" src="https://user-images.githubusercontent.com/12290822/163423168-a5ad86c6-9267-4dea-bfff-a3633665e4c0.png">

**Comment by xkwxdyy** [comment]
> <img alt="Screen Shot 2022-04-14 at 23 28 38" width="752" src="https://user-images.githubusercontent.com/12290822/163423168-a5ad86c6-9267-4dea-bfff-a3633665e4c0.png">

感谢。我没注意到这个，我按照自己的想法以为有误，抱歉

**Comment by hushidong** [comment]
感谢两位！
