### ISSUE TITLE
关于NWAFU格式调整问题

### ISSUE THREAD

**Issue by registor** [hushidong/biblatex-gb7714-2015#128]
胡老师好，

首先感谢你为西北农林科技大学制作了样式文件，极大地减轻了学位论文模板开发与维护的工作量。

在使用中，发现著录列表中有两个小问题，若胡老师方便的话，可以调整一下：

1、希望添加`gbpub=false`参数，以取消自动处理，使用标准样式的方式取消相应项的输出。

2、新的指南里，要求著录列表字号为5号字，因此，建议将`\newcommand\nwafubibfont{\zihao{-5}}`改为`\newcommand\nwafubibfont{\zihao{5}}`。

再次为你的工作表示由衷的感谢！

**Comment by hushidong** [comment]
好的，正好有修改，需要提交新版本。

**Comment by registor** [comment]
非常感谢！
