### ISSUE TITLE
关于 `CCNUthesis` 的 `bbx` 的 bug

### ISSUE THREAD

**Issue by xkwxdyy** [hushidong/biblatex-gb7714-2015#129]
胡老师您好，我是 `CCNUthesis` 的维护者，前段时间发给您邮件但是您没有回复，就想着在这里开一个 issue。

具体问题描述如下：
在中文标点的状态下，当 book 的译者只有两个人时，中间会出现两个逗号。
![image](https://user-images.githubusercontent.com/87134063/163676852-37a8a013-c4af-4de3-8d5f-65a659e69187.png)

MWE：[bib-test.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/8499989/bib-test.zip)

虽然使用的还是英文标点，但是还是希望能够解决一下这个问题，奈何本人对这个了解不多，还是希望得到您的帮助，非常感谢！

**Comment by hushidong** [comment]
感谢，这是一个远古bug了，现在才被你发现，要不是用中文标点是发现不了的。

ctan刚更新，所以这个更新放到下次把，你再测一测看，还有什么问题没有，下次一起更。

修改好的，见附件
[bib-test.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/8500278/bib-test.zip)

**Comment by xkwxdyy** [comment]
测试没问题，太感谢您了！

**Comment by xkwxdyy** [comment]
胡老师您好，我这又遇到问题，发现 book 的 author 之间（两个之间，三个的后两个）逗号后没有空格
<img width="491" alt="image" src="https://user-images.githubusercontent.com/87134063/164736985-c5ddbb5e-601c-4dc9-8462-c3b9ec56e99f.png">

MWE：
[test-bib.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/8541848/test-bib.zip)

希望您有空的时候可以看看

**Comment by hushidong** [comment]
加了个空格

**Comment by hushidong** [comment]
加了个空格
[test-bib.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/8548841/test-bib.zip)

**Comment by xkwxdyy** [comment]
> 加了个空格 [test-bib.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/8548841/test-bib.zip)

非常感谢！测试没问题！
