### ISSUE TITLE
每篇参考文献不用标点做结束符

### ISSUE THREAD

**Issue by gulai22** [hushidong/biblatex-gb7714-2015#138]
参考文献要求的每篇后面不用标点。应该怎么修改bst来删掉结束符。
```
[1] Lee D, Lim M, Han S, et al
[2] Zhang Hua, Wu Zunbao, Shi Keqiang, et al
[3] Stanford University, Department of Civil Engineering
```

**Comment by hushidong** [comment]
谢谢回复@xkwxdyy ，麻烦啦，后面有时间多帮忙解答！！

@gulai22  实现是不难的，关键是你要要把问题确定清楚，如果使用bibtex (样式文件是bst) 你可以请教 @zepinglee ，如果是使用biblatex，请给个例子在这。

**Comment by gulai22** [comment]
> 
好的，谢谢。样式文件是bst，我是在word里面用的bibtex4word插件。刚开始接触不太熟悉，对不起哈。
