### ISSUE TITLE
关于gb7714-NWAFU.bbx中gbnamefmt调整的问题

### ISSUE THREAD

**Issue by registor** [hushidong/biblatex-gb7714-2015#140]
胡老师你好，

由于我一直忽略了我们学校参考文献著录列表规范中“**编著者姓名：姓在前名在后，西文名缩写为首字母(大写)，字母后不加缩写点**”这条规范的正确理解。

因此，可否将gb7714-NWAFU.bbx中的gbnamefmt调整lowercase？还是其它参数更为合适？

在规范中给出的部分示例是：

![image](https://user-images.githubusercontent.com/13491204/170804230-a85d87ea-b6a2-41af-9fa7-5e8f98d005cf.png)

**Comment by hushidong** [comment]
好的，耿老师。

目前的选项gbnamefmt可以控制姓名的 字母大小写、前后顺序、缩写还是全拼，这些选项基本遍历大多数情况。但标点则是另外控制。

姓在前，缩写名在后，可以使用familyahead选项，然后调整一下名缩写后的标点即可。目前已经使用该选项，所以只要调整一下标点就好了。

```
\def\gbcaselocalset{%
    \renewrobustcmd*{\bibinitperiod}{}%
    \renewcommand*{\revsdnamepunct}{}%
    %\renewrobustcmd*{\bibinitdelim}{}%
}


\renewbibmacro*{name:family-given}[4]{%
  \gbcaselocalset%
  \ifuseprefix
    {\usebibmacro{name:delim}{#3#1}%
     \usebibmacro{name:hook}{#3#1}%
     \mkbibcompletenamefamilygiven{%
       \ifdefvoid{#3}
         {}
         {\ifcapital
            {\mkbibnameprefix{\MakeCapital{#3}}\isdot}
            {\mkbibnameprefix{#3}\isdot}%
          \ifprefchar{}{\bibnamedelimc}}%
       \mkbibnamefamily{#1}\isdot
       \ifdefvoid{#4}
         {}
         {\bibnamedelimd\mkbibnamesuffix{#4}\isdot}%
       \ifdefvoid{#2}
         {}
         {\revsdnamepunct\bibnamedelimd\mkbibnamegiven{#2}\isdot}}}
    {\usebibmacro{name:delim}{#1}%
     \usebibmacro{name:hook}{#1}%
     \mkbibcompletenamefamilygiven{%
       \mkbibnamefamily{#1}\isdot
       \ifdefvoid{#4}
         {}
         {\bibnamedelimd\mkbibnamesuffix{#4}\isdot}%
       \ifboolexpe{%
         test {\ifdefvoid{#2}}
         and
         test {\ifdefvoid{#3}}}
         {}
         {\revsdnamepunct}%
       \ifdefvoid{#2}
         {}
         {\bibnamedelimd\mkbibnamegiven{#2}\isdot}%
       \ifdefvoid{#3}
         {}
         {\bibnamedelimd\mkbibnameprefix{#3}\isdot}}}}
```

见最新的更新。

**Comment by zepinglee** [comment]
@registor 上次有人做 CSL 的时候整理了 NWAFU 的参考文献示例。附件是我导出的 bib 格式，可以用于比对测试。
[NWAFU.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/8790488/NWAFU.zip)

**Comment by registor** [comment]
非常感谢，我抓紧时间调整一下。




--
谢谢！
 
耿楠
西北农林科技大学信息工程学院
712100 陕西杨凌西农路22号
电话：029-87092352
***@***.***
           ***@***.***
 
Geng Nan
College of Information Engineering
Northwest A&F University
Shaanxi Yangling
China
712100
Tel: 8602987092352
Email: ***@***.***
           ***@***.***

编辑删除


发件人：Zeping Lee ***@***.***>
发送日期：2022-05-28 12:33:31
收件人：hushidong/biblatex-gb7714-2015 ***@***.***>
抄送人：Geng Nan ***@***.***>,Mention ***@***.***>
主题：Re: [hushidong/biblatex-gb7714-2015] 关于gb7714-NWAFU.bbx中gbnamefmt调整的问题 (Issue #140)

@registor 上次有人做 CSL 的时候整理了 NWAFU 的参考文献示例。附件是我导出的 bib 格式，可以用于比对测试。
 NWAFU.zip

**Comment by registor** [comment]
非常感谢胡老师的悉心指导。




--
谢谢！
 
耿楠
西北农林科技大学信息工程学院
712100 陕西杨凌西农路22号
电话：029-87092352
***@***.***
           ***@***.***
 
Geng Nan
College of Information Engineering
Northwest A&F University
Shaanxi Yangling
China
712100
Tel: 8602987092352
Email: ***@***.***
           ***@***.***

编辑删除


***@***.***" ***@***.***>
发送日期：2022-05-28 12:06:47
收件人：hushidong/biblatex-gb7714-2015 ***@***.***>
抄送人：Geng Nan ***@***.***>,Author ***@***.***>
主题：Re: [hushidong/biblatex-gb7714-2015] 关于gb7714-NWAFU.bbx中gbnamefmt调整的问题 (Issue #140)

好的，耿老师。
目前的选项gbnamefmt可以控制姓名的 字母大小写、前后顺序、缩写还是全拼，这些选项基本遍历大多数情况。但标点则是另外控制。
姓在前，缩写名在后，可以使用familyahead选项，然后调整一下名缩写后的标点即可。目前已经使用该选项，所以只要调整一下标点就好了。
\def\gbcaselocalset{%

    \renewrobustcmd*{\bibinitperiod}{}%

    \renewcommand*{\revsdnamepunct}{}%

    %\renewrobustcmd*{\bibinitdelim}{}%

}





\renewbibmacro*{name:family-given}[4]{%

  \gbcaselocalset%

  \ifuseprefix

    {\usebibmacro{name:delim}{#3#1}%

     \usebibmacro{name:hook}{#3#1}%

     \mkbibcompletenamefamilygiven{%

       \ifdefvoid{#3}

         {}

         {\ifcapital

            {\mkbibnameprefix{\MakeCapital{#3}}\isdot}

            {\mkbibnameprefix{#3}\isdot}%

          \ifprefchar{}{\bibnamedelimc}}%

       \mkbibnamefamily{#1}\isdot

       \ifdefvoid{#4}

         {}

         {\bibnamedelimd\mkbibnamesuffix{#4}\isdot}%

       \ifdefvoid{#2}

         {}

         {\revsdnamepunct\bibnamedelimd\mkbibnamegiven{#2}\isdot}}}

    {\usebibmacro{name:delim}{#1}%

     \usebibmacro{name:hook}{#1}%

     \mkbibcompletenamefamilygiven{%

       \mkbibnamefamily{#1}\isdot

       \ifdefvoid{#4}

         {}

         {\bibnamedelimd\mkbibnamesuffix{#4}\isdot}%

       \ifboolexpe{%

         test {\ifdefvoid{#2}}

         and

         test {\ifdefvoid{#3}}}

         {}

         {\revsdnamepunct}%

       \ifdefvoid{#2}

         {}

         {\bibnamedelimd\mkbibnamegiven{#2}\isdot}%

       \ifdefvoid{#3}

         {}

         {\bibnamedelimd\mkbibnameprefix{#3}\isdot}}}}

见最新的更新。
