### ISSUE TITLE
I found no \citation commands---while reading file liukai.aux  这个报错是为什么

### ISSUE THREAD

**Issue by lkzs** [hushidong/biblatex-gb7714-2015#141]
This is BibTeX, Version 0.99d (MiKTeX 2.9)
The top-level auxiliary file: liukai.aux
I found no \citation commands---while reading file liukai.aux
I found no \bibdata command---while reading file liukai.aux
I found no \bibstyle command---while reading file liukai.aux
(There were 3 error messages)

**Comment by hushidong** [comment]
使用biber编译文献就可以解决。

**Comment by lkzs** [comment]
> 使用biber而不是bibtex编译文献就可以解决。


\documentclass[12pt,a4paper]{ctexrep}
\usepackage[backend=biber,bibstyle=gb7714-2015,%nature,%%加载biblatex宏包，使用参考文献
citestyle=gb7714-2015%,backref=true%%其中后端backend使用biber
]{biblatex}%标注(引用)样式citestyle，著录样式bibstyle都采用gb7714-2015样式

\addbibresource{refer.bib}
\DeclareBibliographyCategory{cited}
\AtEveryCitekey{\addtocategory{cited}{\thefield{entrykey}}}

\begin{document}
这是一个例子\cite{ref1}


\addcontentsline{toc}{chapter}{{\bf 参考文献}}
%\addtolength{\itemsep}{-0.5pt}  %修改参考文献间距

{\renewcommand\baselinestretch{1.25}\selectfont

\begin{thebibliography}{999}
\vspace*{3ex}
\addtolength{\itemsep}{-1.05 em} % 缩小参考文献间的垂直间距
\setlength{\itemsep}{1pt}
   %\bibliographystyle{gbt7714-numerical}
   \def\bibrangedash{ $\sim$ }
   \printbibliography [ category = cited]

\end{thebibliography}
\par}
\end{document}

我用的backend=biber，但还是报同样的错

**Comment by hushidong** [comment]
backend=biber是告诉biblatex宏包的，关键是你自己编译的时候使用的是bibtex。

你用的什么ide？通常像texstudio这样的ide，默认的参考文献工具需要设置的，默认是bibtex，改成默认biber。

测试时最好是使用命令行编译，这样你能看到所有的问题。

```
xelatex jobname
biber jobname
xelatex jobname
```
运行完这三不就能看到结果了。

**Comment by zepinglee** [comment]
`LaTeX2e <2011/06/27>` 这样太远古了吧。

不要使用 CTeX 套装，除非为了投稿基于此的期刊。建议使用最新的 TeX Live 或者 MikTeX。

**Comment by hushidong** [comment]
`biber 8.tex`的命令错了，要用`biber 8` 或者`biber 8.bcf`。

另外如 @zepinglee 所说，ctex套装太老了，biblatex-gb7714-2015至少要texlive2014以后的版本才能用。

你下一个texlive2022用吧。https://mirrors.cqu.edu.cn/CTAN/systems/texlive/Images/texlive2022-20220321.iso
或者类似的地方，国内多数镜像站点都有。

**Comment by lkzs** [comment]
问题解决了，感谢解答！
