### ISSUE TITLE
请求拆分 `gbfootbib` 选项

### ISSUE THREAD

**Issue by AlexaraWu** [hushidong/biblatex-gb7714-2015#146]
希望可以将现在 `gbfootbib` 的设置脚注格式和处理重复文献的两个功能拆分为两个独立的选项。

实际需求是可以在保留处理重复文献功能的同时，可以禁用宏包对脚注格式的修改。

**Comment by hushidong** [comment]
好的。最近看看。

**Comment by hushidong** [comment]
已修改，使用两个选项来控制：gbfootbibfmt实现脚注文献表相同文献用标签替代的功能，gbfootbib实现完全的国标脚注文献表格式。


具体的：
使用`gbfootbibfmt=true`，有：
![图片](https://user-images.githubusercontent.com/20421795/187198935-104cbf4f-b004-4937-979f-3707c534a47f.png)

使用`gbfootbib=true`，有
![图片](https://user-images.githubusercontent.com/20421795/187199082-bb3205e9-9f30-4d6b-8da4-200b0a053bc8.png)

**Comment by hushidong** [comment]
脚注文献表行内的2，似乎应该也调整成非上标。但目前没有做。

**Comment by AlexaraWu** [comment]
我觉得现在这样已经够用了。主要是现在国内很多学位论文模板会自定义 `\thefootnote` 使用字体中自带的带圈数字符号。

**Comment by hushidong** [comment]
好的。
