### ISSUE TITLE
参考文献的名字缩写后面没出现“.” 例如应为Thorne S. K.，但输出的是Thorne S K

### ISSUE THREAD

**Issue by GravYong** [hushidong/biblatex-gb7714-2015#156]

**Comment by sikouhjw** [comment]
修正你的认知，国标没有规定缩写要加 `.`
![图片](https://user-images.githubusercontent.com/49770925/225537827-c56298ef-cbb3-43dd-b407-a640e196d360.png)

**Comment by hushidong** [comment]
刚好在回前一个问题，正好回复一下。

@sikouhjw  对的。

@GravYong 国标是没有点的，如果要求有点，建议将姓名格式改为familyahead，方式如下：

```
\usepackage[backend=biber,style=gb7714-2015,gbnamefmt=familyahead]{biblatex}
```

**Comment by GravYong** [comment]
明白了，谢谢 @sikouhjw @hushidong
