### ISSUE TITLE
让文档标题部分的日期，随发布日期或最新修改日期更新？

### ISSUE THREAD

**Issue by muzimuzhi** [hushidong/biblatex-gb7714-2015#163]
https://github.com/hushidong/biblatex-gb7714-2015/blob/9338d7e53bd6265b364b1c226e04222b371f0bde/biblatex-gb7714-2015.tex#L31
![image](https://user-images.githubusercontent.com/6376638/229981420-4fdf0f42-95c6-477b-ae00-496a3d010ab1.png)
![image](https://user-images.githubusercontent.com/6376638/229981454-ba4ea85f-75af-4719-b486-048a9d35c9ca.png)

从更新历史看，2016-07-01 对应第三次发版，好像不是一个特殊的版本。

**Comment by hushidong** [comment]
还真是比较特殊的日子，所以一直没有改，文档修订时间放脚注里了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Yukai Chou ***@***.***>
Sent: Wednesday, April 5, 2023 12:31:55 PM
To: hushidong/biblatex-gb7714-2015 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hushidong/biblatex-gb7714-2015] 让文档标题部分的日期，随发布日期或最新修改日期更新？ (Issue #163)


https://github.com/hushidong/biblatex-gb7714-2015/blob/9338d7e53bd6265b364b1c226e04222b371f0bde/biblatex-gb7714-2015.tex#L31
[image]<https://user-images.githubusercontent.com/6376638/229981420-4fdf0f42-95c6-477b-ae00-496a3d010ab1.png>
[image]<https://user-images.githubusercontent.com/6376638/229981454-ba4ea85f-75af-4719-b486-048a9d35c9ca.png>

从更新历史看，2016-07-01 对应第三次发版，好像不是一个特殊的版本。

―

**Comment by hushidong** [comment]
倒是可以反一下，把那个日子放脚注好了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by muzimuzhi** [comment]
由 dd50322430eb4baa94252fa37491b920347d9760 修复，现在 `\dateformanual` 使用 `\today`，脚注中描述了 2016-07-01 是文档创建的日子。

https://github.com/hushidong/biblatex-gb7714-2015/blob/b7df51a7232c600afdf8f01c40a408376fe4a38f/biblatex-gb7714-2015.tex#L27-L34
