### ISSUE TITLE
volume填入非数字的问题

### ISSUE THREAD

**Issue by NShiroha** [hushidong/biblatex-gb7714-2015#164]
宏包手册第50页：连续出版物的卷，格式化输入用整数，当有范围时中间用短横线连接，比如:1-4。当无法解析时，输入内容被认为是需要完整打印的内容。但我发现填入非数字时会出现问题，例如，如果使用`volume={第一册}`，输出的结果会是“第第一册卷”。

实际上`volume`也不应该用于专著，按照国标，专著的著录格式为：

> 主要责任者. 题名: 其他题名信息[文献类型标识/文献载体标识]. 其他责任者. 版本项. 出版地: 出版者, 出版年: 引文页码[引用日期]. 获取和访问路径. 数字对象唯一标识符.

诸如“第一册”的信息应包含于“其他题名信息”，但似乎没有这个字段，用`volume`代替又会出现问题。

**Comment by hushidong** [comment]
导言区加上

```
\DeclareFieldFormat[book,inbook,incollection]{volume}%
{\iffieldequalstr{userd}{chinese}{\iffieldint{volume}%
        {%
        \bibstring{serialcn}#1\bibstring{volumecn}%
        }{#1}%
    }%
    {\bibstring{volume}~#1}%
}

```

**Comment by zepinglee** [comment]
国标给出的示例中对应 `volume` 字段的信息还有“美国卷”、“D 辑”，另外还有“上册”等。所以我建议判断 `volume` 的内容，如果是数字则添加前后缀输出“第 2 卷”，否则原文输出。

<img width="785" alt="Screenshot 2023-12-31 at 14 42 38" src="https://github.com/hushidong/biblatex-gb7714-2015/assets/12290822/ef6acc94-c9b0-4286-b7be-95751a76c147">
