### ISSUE TITLE
如何在会议论文集([C])的析出文献中加入主办学会信息？

### ISSUE THREAD

**Issue by dzx-dzx** [hushidong/biblatex-gb7714-2015#168]
![image](https://github.com/hushidong/biblatex-gb7714-2015/assets/31068367/0fa19052-7695-4b47-916e-dd7498435f4d)
学校希望能加入图中"国家环境保护总局生物安全管理办公室"的信息，但其似乎不对应bibtex中的organization，school或institution中的任何一项。

**Comment by dzx-dzx** [comment]
噢我找到了应该是bookauthor。
https://github.com/hushidong/biblatex-gb7714-2015/blob/3542d1dd482fcedf25953d67b9c7756e8f2d0a45/tool/gb7714texteg.dat#L51
https://github.com/hushidong/biblatex-gb7714-2015/blob/3542d1dd482fcedf25953d67b9c7756e8f2d0a45/example.bib#L3127-L3136

**Comment by note286** [comment]
```latex
@inproceedings{xxx,
    author={汪学军},
    title={中国农业转基因生物研发进展与安全管理},
    bookauthor={国家环境保护总局生物安全管理办公室},
    booktitle={中国国家生物安全框架实施国际合作项目研讨会论文集},
    location={北京},
    publisher={中国环境科学出版社},
    year={2002},
    pages={22-25},
}
```

![image](https://github.com/hushidong/biblatex-gb7714-2015/assets/16207292/cf0ac657-7c95-4f54-a2e1-44105a0d98f6)
