### ISSUE TITLE
\setcounter{gbrefcompress}{3}命令报错No counter 'gbrefcompress' defined.

### ISSUE THREAD

**Issue by YanMing-lxb** [hushidong/biblatex-gb7714-2015#176]
\setcounter{gbrefcompress}{3}命令报错No counter 'gbrefcompress' defined.

这是我的代码：
```tex
\RequirePackage[
                backend=biber, % 设置后端程序为biber
                style=gb7714-2015, % 引用和参考文献样式
                gbpub=true, % 出版信息
                gbnamefmt=lowercase, % 姓名小写
                doi=false, % 不显示doi
                url=false, % 不显示url
                gbmedium=false, % 载体标识符不显示OL
                gbpunctin=false, % 关闭inbook,incollection,inproceedings中析出来源文献前//符号
                gbalign=left, % 标签左对齐
                ]{biblatex}
\setcounter{gbrefcompress}{3} % 参考文献引用从第三篇开始压缩
```
看文档看了好久，还是没弄出来，求大佬指点！！！
不胜感激

**Comment by hushidong** [comment]
更新一下biblatex-gb7714-2015，应该就好了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: 焱铭 ***@***.***>
Sent: Wednesday, November 22, 2023 7:25:03 PM
To: hushidong/biblatex-gb7714-2015 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hushidong/biblatex-gb7714-2015] \setcounter{gbrefcompress}{3}命令报错No counter 'gbrefcompress' defined. (Issue #176)


\setcounter{gbrefcompress}{3}命令报错No counter 'gbrefcompress' defined.

这是我的代码：

\RequirePackage[
                backend=biber, % 设置后端程序为biber
                style=gb7714-2015, % 引用和参考文献样式
                gbpub=true, % 出版信息
                gbnamefmt=lowercase, % 姓名小写
                doi=false, % 不显示doi
                url=false, % 不显示url
                gbmedium=false, % 载体标识符不显示OL
                gbpunctin=false, % 关闭inbook,incollection,inproceedings中析出来源文献前//符号
                gbalign=left, % 标签左对齐
                ]{biblatex}
\setcounter{gbrefcompress}{3} % 参考文献引用从第三篇开始压缩

看文档看了好久，还是没弄出来，求大佬指点！！！
不胜感激

―

**Comment by YanMing-lxb** [comment]
解决问题了，感谢大佬！
