### ISSUE TITLE
警告：`byeditor+others` 已定义

### ISSUE THREAD

**Issue by AlexaraWu** [hushidong/biblatex-gb7714-2015#193]
今天更新 TeX Live 后出现了新的警告：
```log
Package biblatex Warning: Macro 'byeditor+others' already defined.
(biblatex)                Using \renewbibmacro.
```

<table>
  <thead>
    <tr>
      <td colspan="2">TeX Live 2024</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>biber</code></td>
      <td>v2.20</td>
    </tr>
    <tr>
      <td><code>biblatex</code></td>
      <td>v3.20</td>
    </tr>
    <tr>
      <td><code>biblatex-gb7714-2015</code></td>
      <td>v1.1q</td>
    </tr>
  </tbody>
</table>

**Comment by hushidong** [comment]
好的，后面会修正。

功能是完整的，使用也不影响的。

**Comment by AlexaraWu** [comment]
fixed in d3cfe6774b6e8954b894556b468939f42fbdbbaa
