### ISSUE TITLE
`\parencite[]{}` 的 `[]` 输入页码时的空格问题

### ISSUE THREAD

**Issue by xkwxdyy** [hushidong/biblatex-gb7714-2015#196]
MWE：
```latex
\documentclass{ctexart}
\usepackage[
  backend=biber,
  style=gb7714-2015,
]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}


\parencite[p. 12]{sigfridsson}

\parencite[p.\,12]{sigfridsson}

\printbibliography

\end{document}
```
输出结果为
<img width="208" alt="image" src="https://github.com/hushidong/biblatex-gb7714-2015/assets/87134063/75758795-fd6d-413f-a7b1-aa8e6d2a39de">

可以看到 `p. 12` 的输出结果为正文的空格间距，应该是把 `.` 当做了句号而产生的空格，但是 `p.` 的 `.` 应该是表示省略，不应该有这么大间距？我也不太清楚具体国标规范有没有关于这部分的内容。我个人习惯感觉 `\,` 的距离合理点。

**Comment by hushidong** [comment]
国标没有规定行内的页码怎么表示的，国标只有上标的页码表示。

所以根据自己的需要处理就好了。

**Comment by xkwxdyy** [comment]
好的，谢谢胡老师。

**Comment by mengchaoheng** [comment]
胡老师您好，请问\parencite产生的[]的前后空格，有国标要求吗？我注意到
```
date of update: 2021-05-06 to version v1.0y
(1) 修改顺序编码制 parencite 命令使保留引用标签后面空格。(20210412)
```
为了美观，我需要在\parencite命令前也输入空格，但我们学校的论文规范虽然没有提及，但他给的样式里前后都没空格的。所以我若要取消[]后的空格，应该如何设置？
