### ISSUE TITLE
建议开一个project翻译biblatex和biber文档

### ISSUE THREAD

**Issue by WenboSheng** [hushidong/biblatex-gb7714-2015#2]
你好！更新TL看到了这个项目。文档中提到正在翻译 biblatex 和 biber 的说明文档。建议可以放到github上来。

**Comment by hushidong** [comment]
恩，感谢建议！ 我本想等做的多一些再放上来，因为现在时间不多，白天晚上都没有完整时间，只能抽点时间做，但进展缓慢。你的提议正好，大家一起做最好了。
