### ISSUE TITLE
设置gbfnperpage=true后，跨页段落中的脚标无法准确重置计数

### ISSUE THREAD

**Issue by hwang63130** [hushidong/biblatex-gb7714-2015#207]
问题描述：设置`\gbfnperpage=true`后，如果：1) 在一个段落中有超过一个`\footfullcite`脚注， 且 2)段落因为过长而在PDF中跨页；
则脚注的数字并不会根据页面来重置，而是需等到段落结束后才重置为。

不知道是不是我设置的问题，还是什么原因。具体的情况可以参见附件的tex源代码和生成的PDF，可以看到第二页的第一个脚标数字是3，直到新起一段后脚标数字才被重置为1。

[example.zip](https://github.com/hushidong/biblatex-gb7714-2015/files/15465654/example.zip)

**Comment by hushidong** [comment]
不要用  gbfnperpage=true 好了，这个是采用默认的latex机制设置的，是会存在问题的。

可以采用：[perpage](https://ctan.org/pkg/perpage) 、 [zref-perpage](https://ctan.org/pkg/zref) 、
 [footmisc](https://ctan.org/pkg/footmisc)、[footnpag](https://ctan.org/pkg/footnpag) 宏包替代。

**Comment by hwang63130** [comment]
非常感谢！根据您的建议，用 perpage顺利搞定了！
