### ISSUE TITLE
英文作者去掉关于“和”“等”涉及的空格

### ISSUE THREAD

**Issue by shiyueyong** [hushidong/biblatex-gb7714-2015#208]
- 参考

[1] https://github.com/hushidong/biblatex-gb7714-2015

[2] https://blog.csdn.net/xenonhu/article/details/124686522

- 来源

《统计研究》劳动收入风险测算及其收入分配效应研究——来自机器学习的实证发现

https://tjyj.cbpt.cnki.net/portal/journal/portal/client/paper/c0791a0d33b948c4656caa6fdf26bf5f

该期刊中的文献, 无论中英文作者, “和”“等”前后均无空格

- 问题

英文作者去掉关于“和”“等”涉及的空格： 如`\citet`【 Betts 和 Taylor(2005)】变为【 Betts和Taylor(2005)】，`\cite`【(Betts 和 Taylor, 2005)】变为【(Betts和Taylor, 2005)】；`\citet`【 Stamerjohanns 等(2009)】变为【 Stamerjohanns等(2009)】，`\cite`【(Stamerjohanns 等, 2009)】变为【(Stamerjohanns等, 2009)】

根据上面的参考网页, 中文“和”无空格是`gb7714-2015ay`中默认设置, 尝试用`\DefineBibliographyStrings`解决其他: `andothersincitecn={\unspace 等}`可以解决中文“等”无空格; 其他尝试解决英文“和”“等”的方法不得法.

MWE(Minimal Working Example)如下:

```latex
%%% browed from https://github.com/hushidong/biblatex-gb7714-2015/issues/69

\documentclass{article}
\usepackage{ctex}
\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015]{biblatex}

%%% see 《biblatex-gb7714-2015 ( 胡振震 2024-05-17 ).pdf》for details
\ExecuteBibliographyOptions{maxcitenames=2,mincitenames=1}
%
\ExecuteBibliographyOptions{gbcitelocal=chinese}
\DefineBibliographyStrings{english}{
    andothersincitecn={\unspace 等}, % 有效
    andothersincite={\unspace 等}, %无效
    andincite = {\unspace 和 \unspace}, %无效
}


\usepackage{filecontents}
\begin{filecontents}{sources.bib}
@article{chen2005zhulu,
    title={著录文后参考文献的规则及注意事项},
    author={陈浩元},
    journal={编辑学报},
    volume={17},
    number={6},
    pages={413--415},
    year={2005}
}
@book{chu2004tushu,
    title={图书馆数字参考咨询服务研究},
    author={初景利 and 陈浩元},
    year={2004},
    address={北京},
    publisher={北京图书馆出版社}
}
@article{yuan2012lana,
    author       = {袁训来 and 陈哲 and 肖书海},
    title        = {蓝田生物群: 一个认识多细胞生物起源和早期演化的新窗口--篇一},
    journal      = {科学通报},
    year         = {2012},
    volume       = {57},
    number       = {34},
    pages        = {3219},
}
@book{lamport1986document,
    title={Document Preparation System},
    author={Lamport, Leslie},
    year={1986},
    publisher={Addison-Wesley Reading, MA}
}
@article{betts2005aging,
    title={Aging reduces center-surround antagonism in visual motion processing},
    author={Betts, Lisa R and Taylor, Christopher P},
    journal={Neuron},
    volume={45},
    number={3},
    pages={361--366},
    year={2005},
    publisher={Elsevier}
}
@article{stamerjohanns2009mathml,
    title={{MathML}-aware article conversion from {LaTeX}},
    author={Stamerjohanns, Heinrich and Ginev, Deyan and David, Catalin and Misev, Dimitar and Zamdzhiev, Vladimir and Kohlhase, Michael},
    journal={Towards a Digital Mathematics Library},
    volume={16},
    number={2},
    pages={109--120},
    year={2009},
    publisher={Masaryk University Press}
}
\end{filecontents}
\addbibresource[location=local]{sources.bib}

\usepackage[hidelinks]{hyperref}

\begin{document}

中文1作者: \citet{chen2005zhulu}blablabla, blablabla\cite{chen2005zhulu}

中文2作者: \citet{chu2004tushu}blablabla, blablabla\cite{chu2004tushu}

中文3作者及以上: \citet{yuan2012lana}blablabla, blablabla\cite{yuan2012lana}

英文1作者: \citet{lamport1986document}blablabla, blablabla\cite{lamport1986document}

英文2作者: \citet{betts2005aging}blablabla, blablabla\cite{betts2005aging}

英文3作者及以上: \citet{stamerjohanns2009mathml}blablabla, blablabla\cite{stamerjohanns2009mathml}

\printbibliography
\end{document} 
```

**Comment by hushidong** [comment]
经济学研究, 用chinese-erj试试。

你是要做模板还是要投稿？这种刊的投稿是不是都是word？如果是word，那么就没有必要在意latex中的空格了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: shiyueyong ***@***.***>
Sent: Thursday, July 25, 2024 10:42:31 AM
To: hushidong/biblatex-gb7714-2015 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hushidong/biblatex-gb7714-2015] 英文作者去掉关于“和”“等”涉及的空格 (Issue #208)


  *   参考

[1] https://github.com/hushidong/biblatex-gb7714-2015

[2] https://blog.csdn.net/xenonhu/article/details/124686522

  *   来源

《统计研究》劳动收入风险测算及其收入分配效应研究――来自机器学习的实证发现

https://tjyj.cbpt.cnki.net/portal/journal/portal/client/paper/c0791a0d33b948c4656caa6fdf26bf5f

该期刊中的文献, 无论中英文作者, “和”“等”前后均无空格

  *   问题

英文作者去掉关于“和”“等”涉及的空格： 如\citet【 Betts 和 Taylor(2005)】变为【 Betts和Taylor(2005)】，\cite【(Betts 和 Taylor, 2005)】变为【(Betts和Taylor, 2005)】；\citet【 Stamerjohanns 等(2009)】变为【 Stamerjohanns等(2009)】，\cite【(Stamerjohanns 等, 2009)】变为【(Stamerjohanns等, 2009)】

根据上面的参考网页, 中文“和”无空格是gb7714-2015ay中默认设置, 尝试用\DefineBibliographyStrings解决:其他: andothersincitecn={\unspace 等}可以解决中文“等”无空格; 其他尝试解决英文“和”“等”的方法不得法.

MWE(Minimal Working Example)如下:

%%% browed from https://github.com/hushidong/biblatex-gb7714-2015/issues/69

\documentclass{article}
\usepackage{ctex}
\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015]{biblatex}

%%% see 《biblatex-gb7714-2015 ( 胡振震 2024-05-17 ).pdf》for details
\ExecuteBibliographyOptions{maxcitenames=2,mincitenames=1}
%
\ExecuteBibliographyOptions{gbcitelocal=chinese}
\DefineBibliographyStrings{english}{
    andothersincitecn={\unspace 等}, % 有效
    andothersincite={\unspace 等}, %无效
    andincite = {\unspace 和 \unspace}, %无效
}


\usepackage{filecontents}
\begin{filecontents}{sources.bib}
@article{chen2005zhulu,
    title={著录文后参考文献的规则及注意事项},
    author={陈浩元},
    journal={编辑学报},
    volume={17},
    number={6},
    pages={413--415},
    year={2005}
}
@book{chu2004tushu,
    title={图书馆数字参考咨询服务研究},
    author={初景利 and 陈浩元},
    year={2004},
    address={北京},
    publisher={北京图书馆出版社}
}
@article{yuan2012lana,
    author       = {袁训来 and 陈哲 and 肖书海},
    title        = {蓝田生物群: 一个认识多细胞生物起源和早期演化的新窗口--篇一},
    journal      = {科学通报},
    year         = {2012},
    volume       = {57},
    number       = {34},
    pages        = {3219},
}
@book{lamport1986document,
    title={Document Preparation System},
    author={Lamport, Leslie},
    year={1986},
    publisher={Addison-Wesley Reading, MA}
}
@article{betts2005aging,
    title={Aging reduces center-surround antagonism in visual motion processing},
    author={Betts, Lisa R and Taylor, Christopher P},
    journal={Neuron},
    volume={45},
    number={3},
    pages={361--366},
    year={2005},
    publisher={Elsevier}
}
@article{stamerjohanns2009mathml,
    title={{MathML}-aware article conversion from {LaTeX}},
    author={Stamerjohanns, Heinrich and Ginev, Deyan and David, Catalin and Misev, Dimitar and Zamdzhiev, Vladimir and Kohlhase, Michael},
    journal={Towards a Digital Mathematics Library},
    volume={16},
    number={2},
    pages={109--120},
    year={2009},
    publisher={Masaryk University Press}
}
\end{filecontents}
\addbibresource[location=local]{sources.bib}

\usepackage[hidelinks]{hyperref}

\begin{document}

中文1作者: \citet{chen2005zhulu}blablabla, blablabla\cite{chen2005zhulu}

中文2作者: \citet{chu2004tushu}blablabla, blablabla\cite{chu2004tushu}

中文3作者及以上: \citet{yuan2012lana}blablabla, blablabla\cite{yuan2012lana}

英文1作者: \citet{lamport1986document}blablabla, blablabla\cite{lamport1986document}

英文2作者: \citet{betts2005aging}blablabla, blablabla\cite{betts2005aging}

英文3作者及以上: \citet{stamerjohanns2009mathml}blablabla, blablabla\cite{stamerjohanns2009mathml}

\printbibliography
\end{document}

―

**Comment by shiyueyong** [comment]
@hushidong 谢谢hushidong先生回复, 我是尝试用来写论文做初稿的（至于终稿用tex或doc后续视情况而定，现在基于pandoc可以一定程度上将tex转化），因为以前用tex习惯了（用natbib和bst）。尝试用biblatex：在这过程中，英文期刊相应的定制没那么复杂和繁琐（即使有，搜索stack, github等也可以基本解决；tex主要是应用套模板）；中文方面涉及biblatex论系统性、全面性、时效性等全网基本是hushidong先生您的开发工作！

您说的chinese-erj我有了解和测试, 事实上您《biblatex-gb7714-2015.pdf》中摘要提到的几个样式我都浅尝过...

《统计研究》https://tjyj.cbpt.cnki.net/ 相比您定制的《经济研究》http://www.erj.cn/ （chinese-erj），局部有些地方还是有不一样。。。

事实上，我个人觉得，如果所有的中文本科、硕士、博士学位论文，以及所有正规的主流的中文期刊等除了word模板外应该都要有tex模板（以及有相应的biblatex参考文献定制，直接对接标准），这样格式统一方面可以得到很大程度上的保证，而且由于tex是开源的编程的，在现今时代代码自动化方面可能相较闭源的word更有优势。。。这涉及很多工作，需要有关机构方面政策、人力财力物力等的支持。。。

回顾往昔，虽然可能每每陷入tex报错、搜索解决的步骤，但是还是在用它；也久病成医、慢慢积累了一定经验。。。

btw, 中文期刊中理工科的tex和bib其实还好，繁琐的是社科和文科的一些期刊的tex和bib定制！事实上，有时也在嘀咕，参考文献主要是告诉人们按图索骥、找到别人的研究工作，搞那麽多花样干嘛！而且有些期刊的参考文献逻辑也很奇怪！后来想想，人家已经存在了，不管合不合理，如果可以的话你也可以不理，心平气和地解释成为“多样性”！

**Comment by hushidong** [comment]
你留个邮箱，这两天，我网页上github不方便，你的要求是能实现的。我直接把文件发给你。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hushidong** [comment]
获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hushidong** [comment]
就是这个文件，我用365邮箱附上来了。你先试一下看看。

为了快速实现考虑，这么处理可能会带来其他一些问题。你试试看，如果没有问题自然最好了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shiyueyong** [comment]
@hushidong 谢谢！我的邮箱收到了您的4封邮件，但是没有附件。。。不要紧，假期您应该也在忙或者休整，正如您所说【如果是word，那么就没有必要在意latex中的空格了】，而且还是稿件草稿阶段。。。其实从逻辑和美观上，英文作者family name “和”“等”默认有空格也是合理的。。。

**Comment by shiyueyong** [comment]
@hushidong 借贵宝地借此机会，顺便请教hushidong先生，如何【中文文献(article, book等)不变, 英文文献将年份year提前放到作者author和标题title之间】？PS: 以您的方便，再次打搅致歉！

即将 (中文部分保持不变)

```latex
[1] 李国平, 张文彬. 地方政府环境规制及其波动机理研究——基于最优契约设计视角[J]. 中国人口·资源与环境, 2014, 24(10):24-31.
[2] 代昀昊, 王晓允, 童心楚. 从共享经济到低碳经济——来自共享单车平台进驻的证据[J]. 数量经济技术经济研究, 2024, 41(4):111-130.
[3] TAPSCOTT D, The Digital Economy: Promise and Peril in the Age of Networked Intelligence[M], New York: McGraw-Hill, 1996.
[4] ZHANG B, TIAN X, Economic transition under carbon emission constraints in China: An evaluation at the city level[J], Emerging Markets Finance and Trade, 2019, 55(6), 1280-1293.
[5] XIE W, CHAPMAN A, YAN T, Do environmental regulations facilitate a low-carbon transformation in China’s resource-based cities?[J], International journal of environmental research and public health, 2023, 20(5), 4502.
```

变为

```latex
[1] 李国平, 张文彬. 地方政府环境规制及其波动机理研究——基于最优契约设计视角[J]. 中国人口·资源与环境, 2014, 24(10):24-31.
[2] 代昀昊, 王晓允, 童心楚. 从共享经济到低碳经济——来自共享单车平台进驻的证据[J]. 数量经济技术经济研究, 2024, 41(4):111-130.
[3] TAPSCOTT D, 1996, The Digital Economy: Promise and Peril in the Age of Networked Intelligence[M], New York: McGraw-Hill.
[4] ZHANG B, TIAN X, 2019, Economic transition under carbon emission constraints in China: An evaluation at the city level[J], Emerging Markets Finance and Trade, 55(6), 1280-1293.
[5] XIE W, CHAPMAN A, YAN T, 2023, Do environmental regulations facilitate a low-carbon transformation in China’s resource-based cities?[J], International journal of environmental research and public health, 20(5), 4502.
```

搜索网页和大模型, 给了`\DeclareBibliographyDriver` 和`\renewbibmacro*`两种解决方案, 但测试不达预期... 


MWE(Minimal Working Example)如下:

```latex
\documentclass{article}
\usepackage{ctex}
\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015]{biblatex}

%% 中文文献不变, 英文文献unit间隔等用逗号
\renewcommand*{\newunitpunct}{%
\iffieldequalstr{userd}{chinese}{\adddot\addspace}{\addcomma\addspace}}
\renewcommand*{\bibpagespunct}{%
\iffieldequalstr{userd}{chinese}{\addcolon\addthinspace}{\addcomma\addspace}}

%% 中文文献不变, 英文文献将年份year提前放到作者author和标题title之间
%????

\usepackage{filecontents}
\begin{filecontents}{sources.bib}
@article{李国平2014,
  title={地方政府环境规制及其波动机理研究——基于最优契约设计视角},
  author={李国平 and 张文彬},
  journal={中国人口{\textperiodcentered} 资源与环境},
  volume={24},
  number={10},
  pages={24--31},
  year={2014}
}
@article{dai2024from,
  title={从共享经济到低碳经济——来自共享单车平台进驻的证据},
  author={代昀昊 and 王晓允 and 童心楚},
  journal={数量经济技术经济研究},
  volume={41},
  number={4},
  pages={111--130},
  year={2024}
}
@book{tapscott1996digital,
  title={The Digital Economy: Promise and Peril in the Age of Networked Intelligence},
  author={Tapscott, Don},
  year={1996},
  publisher={McGraw-Hill},
  address={New York}
}
@article{zhang2019economic,
  title={Economic transition under carbon emission constraints in China: An evaluation at the city level},
  author={Zhang, Bingbing and Tian, Xi},
  journal={Emerging Markets Finance and Trade},
  volume={55},
  number={6},
  pages={1280--1293},
  year={2019},
  publisher={Taylor \& Francis}
}
@article{xie2023environmental,
  title={Do environmental regulations facilitate a low-carbon transformation in China’s resource-based cities?},
  author={Xie, Wancheng and Chapman, Andrew and Yan, Taihua},
  journal={International journal of environmental research and public health},
  volume={20},
  number={5},
  pages={4502},
  year={2023},
  publisher={MDPI}
}
\end{filecontents}
\addbibresource[location=local]{sources.bib}

\usepackage[hidelinks]{hyperref}

\begin{document}

\nocite{*}
\printbibliography
\end{document} 
```

**Comment by hushidong** [comment]
你留个邮箱，我直接发你邮箱。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zepinglee** [comment]
> 现在基于pandoc可以一定程度上将tex转化

@shiyueyong pandoc 可以将 biblatex 生成的参考文献表转为 Word 吗？

**Comment by hushidong** [comment]
转不了，没有从bib生成制定格式文本的过程。

用csl是可以的。我之前用csl转过，但格式也会有问题，需要手动调的多。

最后用的方式是，用pandoc转引用标注，而文献表直接从pdf复制，这样要调的格式少，通常只要调换行带来的问题。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shiyueyong** [comment]
@hushidong 好的, 我的邮箱是 syywdaAT126.com  (AT=@), 谢谢!

**Comment by shiyueyong** [comment]
@zepinglee 只能【一定程度上的转化】，主要是tex数学符号和公式部分（偏数学概率统计计量数学会稍多些，word无论方便度和美观度较tex个人觉得有不逮）。。。正如 @hushidong 所说，word用csl, 但中文化目前就个人的了解还不够（可能信息有延迟，之前也浅尝折腾过一点），不能直接像biblatex加工如谷歌学术提取的bib (一种方法是另加关键词)，虽然无不可但总归稍显麻烦，这也是我尝试接触biblatex的主因。。。定制好bibstyle和citestyle，论文tex定稿后，如 @hushidong 所说， 剩下考虑【文献表直接从pdf复制，这样要调的格式少，通常只要调换行带来的问题】。。。

只能不断尝试，尽量调整，寻找适合自己的。。。

**Comment by hushidong** [comment]
后面那个问题见



获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hushidong** [comment]
给你发126邮箱

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
