### ISSUE TITLE
biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [hushidong/biblatex-gb7714-2015#21]
Apologies for writing in English.

`biblatex` 3.8(a) has been released and will probably land on TeX live and MikTeX soon (there were some problems getting Biber 2.8 to build that should be resolved now). There are a few changes that also impact your style
 - The field `extrayear` is now `extradate`, macros that used `extrayear` in their names have also been renamed. Some macros with `labelyear` in the name now have `labeldate` instead.
 - `\DeclareSortingScheme` is now called `\DeclareSortingTemplate`

Backwards compatibility code for both changes is in place, but it would be appreciated if styles were to adopt the new naming conventions.

The complete list of changes can be found in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki. Feel free to look around, maybe one of the new features can be useful to your style.

**Comment by hushidong** [comment]
Thank you for your advice!

The two changes you mentioned `extrayear -> extradate` and `\DeclareSortingScheme -> \DeclareSortingTemplate`
will really impact the style gb7714-2015.

I will follow you advice, look over the changes in biblatex 3.8(a) and deal the style's compatibility with it.

Thanks again!
