### ISSUE TITLE
\textcite{} 在正文中的格式

### ISSUE THREAD

**Issue by ghiclgi** [hushidong/biblatex-gb7714-2015#27]
希望可以在正文中直接使用biblatex 的`\textcite{}`命令，得到国标2015中10.2.2的格式。
国标的对多著者在正文中的标注要求是指标第一人的姓：
> Chen et el.(1981)
> 陈某 等(1981)

现在直接用`\textcite{}`得到的只是
> Chen, et el. (1981)
> 陈某, 等 (1981)

不知道能否去掉逗号？然后限制只标一个人？

**Comment by ghiclgi** [comment]
好吧，我刚刚在手册的2.2.2 节看到了这一部分的说明。不过还是想问一下能否实现？

**Comment by zepinglee** [comment]
现在的参考文献是基于 bibtex/natbib 实现的，不知道你的 `\textcite` 是哪里来的

**Comment by ghiclgi** [comment]
不是啊，这个是基于biblatex 的，所以本来就有`\textcite{}` 命令可以调用

**Comment by zepinglee** [comment]
我看错了

**Comment by hushidong** [comment]
正常作者年制引用是有逗号的，见10.2.4节。而没有逗号的，10.2.2中情况是因为姓名是自己写的，因此你的问题是有没有命令可以就写年份。你有两种方法可以解决:

1. 用cite*或citeyear，比如陈某 等(\cite*{bibtex key})  或 陈某 等(\citeyear{bibtex key})

2. 修改\yearpagescite命令去掉其中的页码，比如:
\DeclareCiteCommand{\yearcite}
  {\printtext{(}\usebibmacro{prenote}}
  {\printfield{year}\printfield{extrayear}}
  {\multicitedelim}
  {\printtext{)}}
