### ISSUE TITLE
著者-年份格式中同一姓的著者的处理

### ISSUE THREAD

**Issue by ghiclgi** [hushidong/biblatex-gb7714-2015#28]
biblatex 中对姓氏相同的作者（如参考文献有多个姓陈的作者），在正文中引用时，会自动加上名字，变成
> ... (Chen B, et al.) ...

不知道这样是否符合国标中的要求呢？

**Comment by hushidong** [comment]
标准没有细说，所以这使用起来看个人倾向了。

如果要严格要求只能用姓，那么可以使用选项
`uniquelist =false`来实现，避免这种为消除歧义增加的扩展。

**Comment by ghiclgi** [comment]
按照手册，我设置了该选项`uniquelist =false`，这使得同一作者的文献在正文中不会用多个著者来区分。但是对只是姓氏相同的作者，正文中生成的引用格式会出现名字。

**Comment by hushidong** [comment]
恩，我弄错了，应该用选项`uniquename=false`

比如:

        \documentclass[twoside]{article}
        \usepackage{xcolor}
        \usepackage{hyperref}
        \usepackage[backend=biber,style=gb7714-2015ay,uniquename=false]{biblatex}
        \usepackage{filecontents}
        \begin{filecontents}{\jobname.bib}
        @Book{Yi2014--,
          Title                    = {Test},
          Address                  = {Address},
          Author                   = {Yi and B and C},
          Publisher                = {Publisher},
          Year                     = {2014}
        }
        @Book{Yi2013--,
          Title                    = {Supersonic and hypersonic nozzle design},
          Address                  = {BeiJing},
          Author                   = {Yi, S H and Zhao, Y X and He, L and Zhang, M L},
          Publisher                = {National Defense Industry Press},
          Year                     = {2013}
        }
        \end{filecontents}
        \addbibresource{\jobname.bib}

        \begin{document}
        \section{multiple keys with set}
        ref\cite{Yi2014--}
        ref\cite{Yi2013--}

        \end{document}

**Comment by ghiclgi** [comment]
国标中的说明：
>倘若只标注著者姓氏无法识别该人名时，可标注著者姓名，例如中国人、韩国人、日本人用汉
字书写的姓名。

所以我这个问题不是问题。

**Comment by hushidong** [comment]
有这说明啊，那还真是呢。
