### ISSUE TITLE
【`gbnamefmt' undefined】更改作者名称大小写 gbnamefmt=lowercase 

### ISSUE THREAD

**Issue by baidut** [hushidong/biblatex-gb7714-2015#31]
```
Package xkeyval Error: `gbnamefmt' undefined in families `blx@opt@pre'. [\blx@processoptions]
```

**Comment by hushidong** [comment]
哎，好几个错别字。手机还是不方便的。我刚用overleaf测了下，没问题。你先更新到新版试一下？

**Comment by baidut** [comment]
问题解决，感谢@hushidong

虽然还是报 warning，但大小写没问题了。
Package biblatex Warning: Conflicting options.

开始用 tlmgr.exe 升级包，估计还是没有升级到最新版，我把项目里面的 bbx,cbx 覆盖了之后就正常了

\texlive\texmf-dist\tex\latex\biblatex-gb7714-2015
