### ISSUE TITLE
参考文献标题名

### ISSUE THREAD

**Issue by AlexaraWu** [hushidong/biblatex-gb7714-2015#35]
能不能默认不修改参考文献标题名？或者提供一个选项开关？

之前在改中文模版为英文模版时遇到这个问题，`ctex` 包可以对 `\refname` 或 `\bibname` 作出修改，但最后被 `biblatex-gb7714-2015` 的定义覆盖了。

FYI: [CTeX-org/ctex-kit#350](https://github.com/CTeX-org/ctex-kit/issues/350)

**Comment by hushidong** [comment]
不设置也是不行的，因为biblatex已经把他重定义了。

可以有三种方式改标题:

1. 在printbibliography命令中加title选项改

2.\DefineBibliographyStrings{hlanguagei}{hdefnitionsi}
把本地话字符串改了。

3.重定义bibname宏，方法见biblatex手册。

我不详细打出来了，用的手机，抱歉。

**Comment by AlexaraWu** [comment]
原来如此，受教了。
