### ISSUE TITLE
textcite 中作者与年份之间的逗号问题

### ISSUE THREAD

**Issue by ilupin** [hushidong/biblatex-gb7714-2015#36]
在正文中使用 textcite 会在作者和年份之间插入逗号，例如 “作者, (年份) 发现 ...”，但一般行文时其实不会插入逗号，在 gb7714-2015 中也没有发现这样的要求和例子（10.2.4 节的正文示例中用的是类似 parencite 的格式）。

此外，有多个作者时，textcite 也会在第一作者后加上逗号，例如 “第一作者, 等, (年份)”，在正文中一般也不会这样写。我以为 gb7714-2015 只是明确对文后的文献列表作这样的格式要求。

尽管可以用其他命令或设置不插入逗号，但我认为直接让 textcite 符合一般行文习惯更好一些。

#27  也提到了这个问题。

**Comment by hushidong** [comment]
这看来是个常见需求了，你着急的话可以先用 #30
中提到的改法来实现一下，我稍后改动再放上来。

**Comment by hushidong** [comment]
这个问题，我之前没有深究。这次正好进行完整梳理。目前对于高版本biblatex已经测试完毕，低版本的biblatex兼容性因为身边暂没有环境还没测试。你可以看我下面的回复，两种样式均做了测试，你可以运行试试看，是否已经达到了要求。

**Comment by hushidong** [comment]
\documentclass[twoside]{article}
\usepackage{ctex}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{lipsum}
\usepackage[top=2cm,bottom=1cm,left=3cm,right=3cm]{geometry}

\usepackage[backend=biber,style=gb7714-2015]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@ARTICLE{徐伟康2010对,
  AUTHOR = {徐伟康},
  DATE = {2010},
  JOURNALTITLE = {经济研究},
  NUMBER = {5},
  PAGES = {139--148},
  TITLE = {对《 消费者价格指数与生产者价格指数: 谁带动谁?》 一文的质疑},
  USERA = {J},
}

@ARTICLE{徐伟康2011,
  AUTHOR = {徐伟康 and others},
  DATE = {2011},
  JOURNALTITLE = {经济研究},
  NUMBER = {5},
  PAGES = {139--148},
  TITLE = {对《 消费者价格指数与生产者价格指数: 谁带动谁?》 一文的质疑},
  USERA = {J},
}

@ARTICLE{杨光2015经济波动,
  AUTHOR = {杨光 and 孙浦阳 and 龚刚 and 徐伟康},
  DATE = {2015},
  JOURNALTITLE = {经济研究},
  NUMBER = {2},
  PAGES = {47--60},
  TITLE = {经济波动, 成本约束与资源配置},
  VOLUME = {50},
}

@INPROCEEDINGS{FOURNEY1971-17-38,
  AUTHOR = {FOURNEY, M E},
  LOCATION = {New York},
  PUBLISHER = {ASME},
  BOOKTITLE = {Symposium on Applications of Holography in Mechanics, August 23-25, 1971, University of Southern California, Los Angeles, California},
  DATE = {1971},
  PAGES = {17--38},
  TITLE = {Advances in holographic photoelasticity},
}

@BOOK{Yi2013--,
  AUTHOR = {Yi, S H and Zhao, Y X and He, L and Zhang, M L},
  LOCATION = {BeiJing},
  PUBLISHER = {National Defense Industry Press},
  DATE = {2013},
  TITLE = {Supersonic and hypersonic nozzle design},
}
\end{filecontents}
    \addbibresource{\jobname.bib}
    %

    \begin{document}
    \section{set title}
    created with biblatex v\versionofbiblatex, last revised at \today; Style Files (gb7714-2015*.*) have version number: \versionofgbtstyle.

\bigskip
    GB/T 7714-2015 标准 10.1.1 节，引用单篇文献：

    文献\cite{徐伟康2010对}提到。文献\cite{FOURNEY1971-17-38}提到。(use cite)\par
    文献\parencite{徐伟康2010对}提到。文献\parencite{FOURNEY1971-17-38}提到。(use parencite)\par
    \textcite{徐伟康2010对}提到。\textcite{FOURNEY1971-17-38}提到。(use textcite)\par
    \authornumcite{徐伟康2010对}提到。\authornumcite{FOURNEY1971-17-38}提到。
    (use authornumcite)\par
    \textcite{徐伟康2011}提到。

\bigskip
    GB/T 7714-2015 标准 10.1.2 节，引用多篇文献：

    文献\cite{杨光2015经济波动,Yi2013--}提到。(use cite)\par
    文献\parencite{杨光2015经济波动,Yi2013--}提到。(use parencite)\par
    \textcite{杨光2015经济波动,Yi2013--}提到。(use textcite)\par
    \authornumcite{杨光2015经济波动,Yi2013--}提到。(use authornumcite)\par


\bigskip
    GB/T 7714-2015 标准 10.1.3 节，多次引用文献：

    文献\pagescite[16]{杨光2015经济波动}提到。
    文献\pagescite[16]{徐伟康2010对}提到。
    文献\pagescite[16]{Yi2013--}提到。
    文献\pagescite[16]{FOURNEY1971-17-38}提到。(use pagescite)\par
    \authornumcite{杨光2015经济波动}提到。
    \authornumcite{徐伟康2010对}提到。
    \authornumcite{Yi2013--}提到。
    \authornumcite{FOURNEY1971-17-38}提到。(use authornumcite)\par

\bigskip
    其它用法：

    文献\cite[见][49页]{杨光2015经济波动}。
    文献\parencite[见][49页]{杨光2015经济波动}。
    见\citeauthor{杨光2015经济波动}\cite{杨光2015经济波动}。
    文献\footnote{脚注中引用文献\footcite{杨光2015经济波动}。}。
    文献\footfullcite{杨光2015经济波动}。


    \printbibliography

    \end{document}

**Comment by hushidong** [comment]
\documentclass[twoside]{article}
\usepackage{ctex}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{lipsum}
\usepackage[top=2cm,bottom=1cm,left=3cm,right=3cm]{geometry}

\usepackage[backend=biber,style=gb7714-2015ay]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@ARTICLE{徐伟康2010对,
  AUTHOR = {徐伟康},
  DATE = {2010},
  JOURNALTITLE = {经济研究},
  KEYWORDS = {徐伟康2010对},
  NUMBER = {5},
  PAGES = {139--148},
  TITLE = {对《 消费者价格指数与生产者价格指数: 谁带动谁?》 一文的质疑},
  USERA = {J},
}

@ARTICLE{徐伟康2011,
  AUTHOR = {徐伟康 and others},
  DATE = {2011},
  JOURNALTITLE = {经济研究},
  NUMBER = {5},
  PAGES = {139--148},
  TITLE = {对《 消费者价格指数与生产者价格指数: 谁带动谁?》 一文的质疑},
  USERA = {J},
}

@ARTICLE{杨光2015经济波动,
  AUTHOR = {杨光 and 孙浦阳 and 龚刚 and 徐伟康},
  DATE = {2015},
  JOURNALTITLE = {经济研究},
  KEYWORDS = {杨光2015经济波动},
  NUMBER = {2},
  PAGES = {47--60},
  TITLE = {经济波动, 成本约束与资源配置},
  VOLUME = {50},
}

@INPROCEEDINGS{FOURNEY1971-17-38,
  AUTHOR = {FOURNEY, M E},
  LOCATION = {New York},
  PUBLISHER = {ASME},
  BOOKTITLE = {Symposium on Applications of Holography in Mechanics, August 23-25, 1971, University of Southern California, Los Angeles, California},
  DATE = {1971},
  PAGES = {17--38},
  TITLE = {Advances in holographic photoelasticity},
}

@BOOK{Yi2013--,
  AUTHOR = {Yi, S H and Zhao, Y X and He, L and Zhang, M L},
  LOCATION = {BeiJing},
  PUBLISHER = {National Defense Industry Press},
  DATE = {2013},
  TITLE = {Supersonic and hypersonic nozzle design},
}
\end{filecontents}
    \addbibresource{\jobname.bib}
    %

    \begin{document}
    \section{set title}
    created with biblatex v\versionofbiblatex, last revised at \today; Style Files (gb7714-2015*.*) have version number: \versionofgbtstyle.

\bigskip
    GB/T 7714-2015 标准 10.2.1 节，引用单篇文献：

    文献\cite{徐伟康2010对}提到。文献\cite{FOURNEY1971-17-38}提到。(use cite)\par
    文献\parencite{徐伟康2010对}提到。文献\parencite{FOURNEY1971-17-38}提到。(use parencite)\par
    徐伟康\yearcite{徐伟康2010对}提到。FOURNEY\yearcite[18]{FOURNEY1971-17-38}提到。(use yearcite)\par
    \textcite{徐伟康2010对}提到。\textcite{FOURNEY1971-17-38}提到。(use textcite)\par
    \textcite{徐伟康2011}提到。

\bigskip
    GB/T 7714-2015 标准 10.2.2 节，引用单篇文献(多个作者的情况)：

    文献\cite{杨光2015经济波动}提到。文献\cite{Yi2013--}提到。(use cite)\par
    文献\parencite{杨光2015经济波动}提到。文献\parencite{Yi2013--}提到。(use parencite)\par
    杨光\ 等\yearcite{杨光2015经济波动}提到。Yi et al. \yearcite{Yi2013--}提到。(use yearcite)\par
    \textcite{杨光2015经济波动}提到。\textcite{Yi2013--}提到。(use textcite)\par


\bigskip
    GB/T 7714-2015 标准 10.2.4 节，多次引用文献：

    文献\pagescite[16]{杨光2015经济波动}提到。
    文献\pagescite[16]{徐伟康2010对}提到。
    文献\pagescite[16]{Yi2013--}提到。
    文献\pagescite[16]{FOURNEY1971-17-38}提到。(use pagescite)\par
    杨光\yearpagescite[17]{杨光2015经济波动}提到。
    徐伟康\yearpagescite[16]{徐伟康2010对}提到。Yi\yearpagescite[17]{Yi2013--}提到。FOURNEY\yearpagescite[17]{FOURNEY1971-17-38}提到。(use yearpagescite)\par

\bigskip
    其它用法：

    文献\cite[见][49页]{杨光2015经济波动}。
    文献\parencite[见][49页]{杨光2015经济波动}。
    见赵耀东(\cite*{杨光2015经济波动})。
    见赵耀东(\citeyear{杨光2015经济波动})。
    文献\footnote{脚注中引用文献\footcite{杨光2015经济波动}。}。
    文献\footfullcite{杨光2015经济波动}。


    \printbibliography

    \end{document}

**Comment by hushidong** [comment]
测试时，样式文件用最新的更新

**Comment by ilupin** [comment]
我测试了最新的版本，确认这个问题已经被妥善地解决了，谢谢～
