### ISSUE TITLE
这个支持语言自动识别et al和“等”吗？

### ISSUE THREAD

**Issue by redleafnew** [hushidong/biblatex-gb7714-2015#37]
可以根据语言，中文的超过三个作用为“等”，英文的为“et al”吗？说明文档中好像没有提到。谢谢

**Comment by hushidong** [comment]
支持的，
等和et al是国标的基本要求，必须要实现的，只是实现的方式问题是自动(完全不用管)还是手动(利用增加的language域判断)，你问的应该是能否实现自动的判断？答案是肯定的。

宏包设计之初，为了实现cjk字符判断就花了不少精力，因为利用tex代码实现判断有一些特殊性在里面，所以到现在2年多过去，判断的方法已经更新了好几轮了。最初用leo liu(刘海洋)给出的代码，利用tex的`符号读取字符的unicode码判断，很长一段时间用的很好。但后来考虑到对gbk编码的兼容性，`方法存在问题。考虑换到另一个思路用CJKsymbol,一些情况下但也面临困难。最后还是考虑利用biblatex的动态数据修改功能来实现的。

这个功能是个基础功能，所以随着在文档中逐步完善，慢慢就没有当做重点介绍了。只是在：
概述的易用性，
1.3.1节bib文件的说明，
1.4节多语言支持
中略有提到。

为了减小说明文档，具体技术细节，已经放到[latex中文参考文献的biblatex解决方案--biblatex 简明使用手册](https://github.com/hushidong/biblatex-solution-to-latex-bibliography)中介绍了。

百闻不如一见，介绍再多，不如动手试一试来的好。

有什么问题，非常欢迎反馈。

**Comment by redleafnew** [comment]
谢谢您及时详细的回复。增加了我学习latex的决心。这个问题几乎没有其他软件可以解决，以前用过很多包括endnote、zotero、Mendeley，都不能解决自动识别et al和等的问题。一定仔细学习一下这个。

多谢。



Best regards!

Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University 
 
发件人： hzzmail@163.com
发送时间： 2018-06-05 07:14
收件人： hushidong/biblatex-gb7714-2015
抄送： redleafnew; Author
主题： Re: [hushidong/biblatex-gb7714-2015] 这个支持语言自动识别et al和“等”吗？ (#37)
支持的，
等和et al是国标的基本要求，必须要实现的，只是实现的方式问题是自动(完全不用管)还是手动(利用增加的language域判断)，你问的应该是能否实现自动的判断？答案是肯定的。
宏包设计之初，为了实现cjk字符判断就花了不少精力，因为利用tex代码实现判断有一些特殊性在里面，所以到现在2年多过去，判断的方法已经更新了好几轮了。最初用leo liu(刘海洋)给出的代码，利用tex的符号读取字符的unicode码判断，很长一段时间用的很好。但后来考虑到对gbk编码的兼容性，方法存在问题。考虑换到另一个思路用CJKsymbol,一些情况下但也面临困难。最后还是考虑利用biblatex的动态数据修改功能来实现的。
这个功能是个基础功能，所以随着在文档中逐步完善，慢慢就没有当做重点介绍了。只是在：
概述的易用性，
1.3.1节bib文件的说明，
1.4节多语言支持
中略有提到。
为了减小说明文档，具体技术细节，已经放到latex中文参考文献的biblatex解决方案--biblatex 简明使用手册中介绍了。
百闻不如一见，介绍再多，不如动手试一试来的好。
有什么问题，非常欢迎反馈。

**Comment by Youguang** [comment]
想问一下是按整篇文章还是按段落（语句）自动识别呢？我用了 [ucas 模版](https://github.com/mohuangrui/ucasthesis)，中文段落是“等， 和”，英文段落并不能自动变成“et al. and”，图注中的英文段落也不行。

**Comment by hushidong** [comment]
是按文献本身的信息判断的，如果要局部修改也可以的，可参考示例：https://github.com/hushidong/biblatex-gb7714-2015/blob/master/egthesis/thesis-ucas-m.tex
