### ISSUE TITLE
关于多语言文献不同格式的设置问题

### ISSUE THREAD

**Issue by Markhng** [hushidong/biblatex-gb7714-2015#39]
在大陆，中文文献基本上使用 GB/T 7714-2015 标准，然而在某些特殊情况，英文等其他语言文献可能会要求使用其他标准。
我想请教以下开发者针对本宏包，如何配置，得以实现对于其他语言的特定格式要求的输出，比如使用 biblatex 默认参考文献格式，或自定义格式。
非常感谢！

**Comment by hushidong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
你好根据你的问题，我理解你的需求可能是这样的，就是不同的语言的文献采用不同的标准来实现。尽管这样可能导致文献的风格不统一，如果在一个相同的文献表中，但如你说所说，也是存在这种可能性的。不同的语言文献如果单单存在一些附加信息，比如等这样的本地化字符串的差异的话，是容易通过babel等宏包和相应的选项来实现的。详见biblatex-gb7714-2015的宏包中提供的 testmultilanay.tex 文件。但这种方式可能并不能满足你的需要。从biblatex-gb7714-2015目前的实现看，如果要实现全局的不同遵守标准的设置的话，还需要修改一下样式的设计，这个问题，还要思考一下如何解决。但如果局部的看，是能够实现一些不同的格式设置的，我们以 book 类为例做讨论，主要的格式包括作者，标题，出版项，页码等。分项来看：(1)作者域格式：目前对于作者有全局选项gbnamefmt，局部域nameformat两种设置方式，因此，利用sourcemap对某种语言的文献设置nameformat为某一个具体的格式，那么就能达到要求。(2)标题域格式：主要通过类似\DeclareFieldFormat{title}{#1}这样的命令，来实现，在设置中做一个判断，如果是某种语言的文献，则设置某种格式，比如做斜体，加引号等。(3)出版项格式：可以通过对 publisher+location+date宏做修改，首先判断文献类型，然后做相应的格式处理，标点等也在内部处理。(4)页码项格式：修改\renewbibmacro*{chapter+pages} 和\DeclareFieldFormat{pages}{#1}，也是先判断语言做对应的处理。可以看到，在目前情况下可以通过这种方式来实现对于不同语言设置不同的格式。想象一下，如果你的需求可以通过全局的设置选项来解决的话，那么可能是这样的，样式仍然采用gb7714-2015，但通过其它选项来设置不同语言的文献为其他样式，这种方式目前还没有具体实现的路径，需要好好考虑一番。你也可以考虑一下，看怎么来设计比较好。


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师

**Comment by Markhng** [comment]
感谢开发者在百忙之中回复这个问题。坦言我不太了解宏包工作的内部机理，但我不知道可不可以经过设置通过比如\encite{}将英文参考导引到英文的格式？

**Comment by hushidong** [comment]
这是一个思路。因为可以进行中英文语言的自动判断，所以这种一引导更多的可能是在单独指定某些文献的格式时用。

目前的问题难点是怎么在一个文献表中，使用两种样式。对于中文使用gb7714,样式，英文使用标准样式，是可以实现的，大体的思路是把所有中文的定制局部化，而全局用标准样式，当遇到中文文献使用局部的gb7714格式。

这段时间事情比较多，先考虑着，等有空了再来实现。

**Comment by hushidong** [comment]
v1.0m版本增加了gb7714-2015ms样式文件，主要是为了在一个文档中使用多种样式，比如中文文献使用GB/T 7714-2015规定的著录格式，而其它语言文献使用biblatex提供的标准样式。这种方式尽管不会很常用，但既然有需求提出，那么就做了实现。

主要的实现原理是把所有的GB/T 7714-2015规定产生的格式修改局部化到每一条文献打印时处理，此时先判断gbstyle选项及文献的语言，当满足要求则使用这些局部化格式修改，否则使用默认的标准样式。这种实现为一篇文档内实现两种样式提供了思路，尽管目前其它语言文献的著录格式是标准样式，但只要对其做格式修改就可以形成符合某种格式规范的样式，比如像ieee，nature等样式都是可以实现的，因此存在中文使用GB/T 7714-2015著录格式，而英文文献使用ieee等著录格式的可能性。测试文档见：
。

**Comment by hushidong** [comment]
中文用国标，英文用标准样式，姓名使用大小写不变姓在前格式，的测试见：

![default](https://user-images.githubusercontent.com/20421795/44159311-973d4800-a0e9-11e8-9c7e-63abbb6623c8.png)

中文用国标，英文用标准样式，姓名使用国标要求，的测试见：

![default](https://user-images.githubusercontent.com/20421795/44159382-c81d7d00-a0e9-11e8-9942-958692d4b3de.png)
