### ISSUE TITLE
url & urldate

### ISSUE THREAD

**Issue by WenboSheng** [hushidong/biblatex-gb7714-2015#4]
使用时发现，如果条目有 url 域的话就会加上[OL]并列出url。这样文献列表很长。所以用 Jabref 去掉了 url ，但是发现urldate 还是会列出来。

是否可以实现这样的功能，如果没有 url的话，就不要列出 urldate了？

**Comment by hushidong** [comment]
这还真是个问题呢，
一般情况下，url都是同时存在的，但有时的确是不需要url。这个问题之前没有考虑到。有两种方式可以修改:
1. 像你那样在bib文件中删除url，然后重定义\renewbibmacro*{url+urldate}，加个判断没有url就不输出
2. 是不删除url，加载包时直接使用url=false选项，然后在标识符格式化指令gbtypeflag中增加该选项的判断。

我想还是按照第2中方式修改，这样可以不用动bib文件了。

这个包你如果发现问题，你有空也自己直接改吧。

**Comment by hushidong** [comment]
好久了，现在应该是兼容处理了url选项，直接使用url选项让它不输出了。
