### ISSUE TITLE
上标引用有多余的空白

### ISSUE THREAD

**Issue by zepinglee** [hushidong/biblatex-gb7714-2015#40]
文档第 6 页，上标的引用有多余的空白
<img width="392" alt="screen shot 2018-08-06 at 9 20 15 pm" src="https://user-images.githubusercontent.com/12290822/43718848-898c640c-99be-11e8-89a3-056691906f42.png">

**Comment by hushidong** [comment]
感谢，
你真仔细！
这个空格是在cbx文件更新时引入的，已做处理。pdf文档之前没有做新的编译所以带着错误。

**Comment by hushidong** [comment]
这个问题也来源于没有写一个好的测试，内容多了以后，没那么仔细查了。

问题已解决，ctan上也做了更新。

**Comment by zepinglee** [comment]
我之前试了一下 l3build，但是对 bibtex 不太友好，不知道是否适合 biblatex

**Comment by hushidong** [comment]
l3build怎么个用法？我不太熟悉？所以想请教一下，如果有好用的特性，我去深入了解一下。

但我有个疑惑，像这里这种错误，如果不看pdf是不知道的，因为整个编译也没报错，也没警告，最多算哪个地方不严谨，缺些注释，l3build不好测出来吧？
