### ISSUE TITLE
关于 BibTeX 的兼容性

### ISSUE THREAD

**Issue by zepinglee** [hushidong/biblatex-gb7714-2015#41]
我注意到你的 `gbstrict` 选项是为了兼容 `BibTeX` 的 `language` 域。

我在设计 bst 时的思路是，尽可能遵循 BibTeX 的传统，但是因国标而新增的项目按照 BibLaTeX 的接口。
所以我决定把这个地方的 `language` 改成 `langid`，然后你应该可以去掉这个选项了吧？

另外关于我的 bst 的 entry type 和 filed 你有什么改进的建议？

**Comment by hushidong** [comment]
嗯，可以去掉它。但也可以留着做其他用，可能也需要排除一切biblatex在driver中提供的而gb不需要的域。


我觉得你的language和langid可以同时用，虽然biblatex中两者还是有点差别的，langid主要是在不同语言的本地化字符串切换时用。但对于咱们国标来说，无所谓用哪个。我想从用户的角度出发可能用language表示语言可能更自然一些。language或langid都留着吧，我按照你的设置把language域与langid与等同了，所以你那也没必要改。

关于条目类型和域，新的那些类型如dataset等，我都是学你的，newspaper咱们都是一致的。建议的话，可能就是在兼容性方面有点：
比如
mastersthesis 或 phdthesis 是不是考虑了有就用 thesis的情况？
techreport 是不是考虑了就用report的情况？
online是不是有用www，electronic的情况？
域方面：
edition和version是不是有混用的情况？

这些我不是很了解你那边的处理，可能你已经处理了，没有的话，可以考虑一下。

**Comment by zepinglee** [comment]
感谢指导！

BibTeX 标准是没有 thesis, report, online, www, online 和 version 的，所以标准的 BibTeX bib 使用起来是绝对没问题的，不过我觉得可以加上项目作为 alias。
