### ISSUE TITLE
正文引用中，有些只用姓氏表示，有些引用还带有名字，有些只有名字的首字母，如何做到一致？

### ISSUE THREAD

**Issue by lixiangnlp** [hushidong/biblatex-gb7714-2015#42]
正文引用中，有些只用姓氏表示，有些引用还带有名字，有些只有名字的首字母，如何做到一致？

**Comment by hushidong** [comment]
加载biblatex时，加上选项 uniquename=false 试试。

参考一下 #28 。

**Comment by lixiangnlp** [comment]
谢谢，这个选项确实可以。我说的首字母的问题，是由于不同文章同一作者有的有middle name有的没有，这样生成的结果就是有的同一个作者的名字格式不一样，不过这个问题不大，谢谢。
