### ISSUE TITLE
next version of biblatex will drop xstring

### ISSUE THREAD

**Issue by moewew** [hushidong/biblatex-gb7714-2015#45]
For the upcoming version we are currently planning on getting rid of `xstring` code in `biblatex`. As a consequence `biblatex` would not require `xstring` any more and would not load the `xstring` package itself any more. `biblatex` styles that need `xstring` would have to load the package explicitly themselves. See https://github.com/plk/biblatex/pull/816 for the current state of affairs.

Your style uses some `xstring` commands and loads `xstrings` explicitly. But the Google translation of the comment in `\RequirePackage{xstring}%解决texlive2015的biblatex3.0不加载xstring包的问题` makes me think that this is for compatibility reasons only. If the changes go through as planned, the line would be required for all newer versions as well (so it wouldn't be for compatibility with older versions any more).

Even if it turns out that the change can not go through as planned, it is still a very good idea to load `xstring` explicitly if your style needs it.

We are hoping to release a new version of `biblatex` in the not too distant future (I can't promise any ETA as of now, there will be a pre-release announcement on [comp.text.tex](https://groups.google.com/forum/#!forum/comp.text.tex)). You can learn more about the upcoming changes in https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md. If you can find time to test your style against the new dev version (https://sourceforge.net/projects/biblatex/files/development/, you'll also need Biber 2.12 from https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/) feedback would be appreciated.

**Comment by hushidong** [comment]
I noticed the pdftex' compilatin problem（ https://github.com/plk/biblatex/pull/813), I think this problem will be solved after dropping xstring.

I use xstring to judge the version of biblatex to make some adaption thus to get same output with different version' biblatex. I want to determine the precise version, so \@ifpackagelater can not meet fully.  I use the following code to do it, is there a better mechanism about it?

\providetoggle{iftlfive}\togglefalse{iftlfive}%用于处理biblatex3.2之前的版本 \providetoggle{iftlsix}\togglefalse{iftlsix}%用于处理biblatex3.3开始改变的新的姓名机制后版本 \providetoggle{iftlseven}\togglefalse{iftlseven}%用于处理biblatex3.7的兼容性 \providetoggle{iftleight}\togglefalse{iftleight}%用于处理biblatex3.8到3.9的兼容性 \providetoggle{iftlnine}\togglefalse{iftlnine}%用于处理biblatex10的兼容性 \providetoggle{iftlatest}\toggletrue{iftlatest}%假设是最新版biblatex \StrBefore{\abx@version}{.}[\numinteger]%以点区分整数和小数 \StrBehind{\abx@version}{.}[\numdigital]%小数部分可能带字母所以需将其去掉，见下一行代码 \IfInteger{\numdigital}{}{\StrGobbleRight{\numdigital}{1}[\numdigital]} \ifnumcomp{\numinteger}{=}{3}{ \ifnumcomp{\numdigital}{=}{10}{\toggletrue{iftlnine}\togglefalse{iftlatest}}{}%3.10版本 \ifnumcomp{\numdigital}{<}{10}{\ifnumcomp{\numdigital}{>}{7}{\toggletrue{iftleight}\togglefalse{iftlatest}}{}}{}%>3.8版本用iftleight=true表示 \ifnumcomp{\numdigital}{=}{7}{\toggletrue{iftlseven}\togglefalse{iftlatest}}{}%3.7版本用iftlseven=true表示 \ifnumcomp{\numdigital}{<}{7}{\ifnumcomp{\numdigital}{>}{2}{\toggletrue{iftlsix}\togglefalse{iftlatest}}{}}{}%3.3-3.6版本用iftlsix=true表示 \ifnumcomp{\numdigital}{<}{3}{\toggletrue{iftlfive}\togglefalse{iftlatest}}{}%3.0-3.2版本用iftlfive=true表示 }{\ifnumcomp{\numinteger}{>}{3}{ \blx@warning@noline{% biblatex version is >= 4.x.\MessageBreak if errors raised，Please contact biblatex-gb7714-2015 pkg author.}% }{ \toggletrue{iftlfive}\togglefalse{iftlatest}%2.x版本统一用iftlfive=true表示 \blx@warning@noline{% biblatex version is <= 2.x.\MessageBreak if errors raised，Please contact biblatex-gb7714-2015 pkg author.}% }} \newcommand\defversion[2]{\csdef{codeversion#1#2}}%定义不同版本的命令 \newcommand\switchversion[2]{\csuse{codeversion#1#2}}%使用不同版本的命令


%% 针对biblatex<3.3版本的选项设置，比如texlive2015中的3.0版%\defversion{3.0}{opt}{ \ExecuteBibliographyOptions{ firstinits=true, %名字有缩写，参考3.1.2.3 Internal }}%% 针对3.3<=biblatex<3.5版本的选项设置，比如texlive2016中的3.4版%\defversion{3.4}{opt}{ \ExecuteBibliographyOptions{ giveninits=true, %名字有缩写，参考3.1.2.3 Internal }}%% 针对3.7<=biblatex<=3.9版本的选项设置，比如texlive2017中的3.7版%\defversion{3.7}{opt}{ \ExecuteBibliographyOptions{ giveninits=true, urldate =edtf, %iso8601 eventdate =edtf, }}%% 针对3.10<=biblatex版本的选项设置，比如texlive2018中的3.11版%\defversion{3.10}{opt}{ \ExecuteBibliographyOptions{ giveninits=true, urldate =gb7714-2015, %iso，iso8601，edtf eventdate =gb7714-2015, }} %% 根据biblatex版本信息，选择选项设置%% 原理方法:如下这种选择机制能自动兼容更新的版本，但对于老版本% 必须要把情况列全。\iftoggle{iftlfive}{\switchversion{3.0}{opt}}{}%biblatex<=3.2\iftoggle{iftlsix}{\switchversion{3.4}{opt}}{}%3.3<=biblatex<=3.6\iftoggle{iftlseven}{\switchversion{3.7}{opt}}{}%biblatex=3.7\iftoggle{iftleight}{\switchversion{3.7}{opt}}{}%3.8<=biblatex<=3.9\iftoggle{iftlnine}{\switchversion{3.10}{opt}}{}%biblatex=3.10\iftoggle{iftlatest}{\switchversion{3.10}{opt}}{}%biblatex最新3.11

**Comment by moewew** [comment]
Yes https://github.com/plk/biblatex/issues/768 and https://github.com/plk/biber/issues/237 which both could be solved by not using `xstring` were my main motivations to get rid of it for `biblatex`.

Naively I would have said that `\@ifpackagelater` is the best way to get the version information. And with two nested `\@ifpackagelater`s it should be possible to pin down the exact version. I haven't tested this, though. What exactly did not work for you when you did that?

Still, there is no problem in your style using `xstring` to extract version information as long as you explicitly load `xstring`. I would prefer `\@ifpackagelater` for that job, but you should do what works for you.

**Comment by hushidong** [comment]
(*^ω^*)  ，nested \@packagelater is a good method, I forget it actrually. thank you!
