### ISSUE TITLE
会议论文“卷号”的标注

### ISSUE THREAD

**Issue by MeetWq** [hushidong/biblatex-gb7714-2015#47]
有些会议论文是有 volume 信息的
谷歌学术上的是这样的：
![2018-12-23_221240](https://user-images.githubusercontent.com/33149974/50384518-b9cb1780-0700-11e9-8319-9fdbda826cbd.png)
latex生成的是这样的：
![2018-12-23_221515](https://user-images.githubusercontent.com/33149974/50384527-d5ceb900-0700-11e9-9840-7276cba1db42.png)

**Comment by hushidong** [comment]
你把这条文献的bib信息贴上来看一下。

**Comment by hushidong** [comment]
对于会议论文，国标没有卷信息要求，所以也没有格式要求。所以目前的是默认的格式。我奇怪的是你的地址为什么没有输出，所以才让你把bib文件的内容放一下。

**Comment by hushidong** [comment]
解决了么？

**Comment by MeetWq** [comment]
地址是我自己删掉的，不要在意。。

@inproceedings{mcghee1977control,
  title = {Control of Legged Locomotion Systems},
  volume = {38},
  booktitle = {Proceedings of the 18th {{Automatic Control Conference}}},
  date = {1977},
  pages = {205-215},
  author = {McGhee, Robert B}
}

我看了国标，确实没有规定，但感觉上面那种方式更合理一点
