### ISSUE TITLE
如何让\bibpubfont仅仅更改出版项中的杂志名、出版地、出版社信息的字体，但是不更改页码、URL、DOI、时间等信息的字体呢？

### ISSUE THREAD

**Issue by registor** [hushidong/biblatex-gb7714-2015#49]
如何让\bibpubfont仅仅更改出版项中的杂志名、出版地、出版社信息的字体，但是不更改页码、URL、DOI、时间等信息的字体呢？

**Comment by hushidong** [comment]
如同我在邮件里给你发的，修改方法

出版项修改下面这个两个宏
\DeclareListFormat{location}{%
  \usebibmacro{list:delim}{#1}%
  #1\isdot
  \usebibmacro{list:andothers}}

\DeclareListFormat{publisher}{%
  \usebibmacro{list:delim}{#1}%
  #1\isdot
  \usebibmacro{list:andothers}}

我看了你们的格式要求，是比较复杂的，但还是可以通过有限修改得到的。

**Comment by hushidong** [comment]
作者年制国标其实没有很细的规定，只是有限的例子，但总体还是规范的。你们的格式要求其实反而要更复杂一些。

**Comment by registor** [comment]
非常感谢你的实时回复，已完成修改。
