### ISSUE TITLE
使用\textcite引用多个作者的文献时的问题

### ISSUE THREAD

**Issue by zwz** [hushidong/biblatex-gb7714-2015#51]
我是这样的配置
```
\usepackage[sorting=none,backend=biber,autocite=superscript,gbpub=false,
  bibstyle=gb7714-2015,citestyle=numeric-comp]{biblatex}
```
发现最终的pdf正文中（不是参考文献列表中），\textcite多个作者的文献有这么几个问题
1. 两个作者姓名之间是半角逗号，这里可以配置为全角逗号或者“和”吗？
2. 当作者超过三个时，第一个作者姓名和后面的“等”之间有一个空格，这个可以去掉吗？

**Comment by hushidong** [comment]
能给个简单示例么。
另外把citestyle改成gb7714-2015

**Comment by hushidong** [comment]
第二个问题试试
%textcite标注命令中的标点设置
\DeclareDelimFormat[textcite]{andothersdelim}{}%

**Comment by hushidong** [comment]
第一个问题试试

\DeclareDelimFormat[bib]{multinamedelim}{和}
 \DeclareDelimFormat[bib]{finalnamedelim}{}

**Comment by hushidong** [comment]
在外出差没带电脑，你先试试，有问题放mwe

**Comment by zwz** [comment]
我尝试了一下，第二个问题可以解决

针对第一个问题，如果设置citestyle=gb7714-2015
当作者大于一个时就会显示等，没有办法重现
所以我还是使用我最开始的设置
然后发现第一个问题似乎应该要设置
`\DeclareDelimFormat[textcite]{finalnamedelim}{和}`才可以

不过我发现还有点问题是 `\textcite{a1,a2,a3}`
最终效果是 `作者列表[1], 作者列表[2], 作者列表[3]`
中间这些逗号是半角，有没有办法设置呢

**Comment by hushidong** [comment]
标注的作者数量问题，设置
maxcitenames=2,mincitenames=1
即可

**Comment by hushidong** [comment]
\renewcommand{\textcitedelim}{、}

试试这个，把顿号改为全角逗号即可。

**Comment by hushidong** [comment]
上mwe是最好的。

**Comment by zwz** [comment]
点赞，谢谢，已经解决问题了！

**Comment by hushidong** [comment]
没有新问题就先关闭啦
