### ISSUE TITLE
找不到\authornumcite等命令

### ISSUE THREAD

**Issue by jiewuza** [hushidong/biblatex-gb7714-2015#52]
查看了文档，开头就提到`提供丰富的标注（引用）命令`
（ps. 第二页第一段末尾的`\textcite(提供主语作者加括号包围年份)`应该是不对的）

正好发现`\authornumcite`是想要的效果，但是发现找不到该命令

这是MWE：
```
\documentclass{article}
\usepackage[AutoFakeBold=true,AutoFakeSlant=true,CJKchecksingle]{xeCJK}[2017/08/08]
\usepackage[sorting=none,backend=biber,autocite=superscript,gbpub=false,
  bibstyle=gb7714-2015,citestyle=numeric-comp]{biblatex}
\addbibresource{my.bib}
\begin{document}

\authornumcite{testkey}           % 这里改成\cite、\textcite都是没有问题的

\printbibliography
\end{document}
```
会报错`Undefined control sequence.`

**Comment by hushidong** [comment]
把citestyle设置成gb7714-2015.



<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png&name=hzzmail&uid=hzzmail%40sjtu.org&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ahzzmail%40sjtu.org%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
hzzmail
邮箱：hzzmail@sjtu.org


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制


在2019年04月25日 18:48，jiewuza<mailto:notifications@github.com> 写道：

查看了文档，开头就提到提供丰富的标注（引用）命令
（ps. 第二页第一段末尾的\textcite(提供主语作者加括号包围年份)应该是不对的）

正好发现\authornumcite是想要的效果，但是发现找不到该命令

这是MWE：

\documentclass{article}

\usepackage[AutoFakeBold=true,AutoFakeSlant=true,CJKchecksingle]{xeCJK}[2017/08/08]

\usepackage[sorting=none,backend=biber,autocite=superscript,gbpub=false,

  bibstyle=gb7714-2015,citestyle=numeric-comp]{biblatex}

\addbibresource{my.bib}

\begin{document}



\authornumcite{testkey}           % 这里改成\cite、\textcite都是没有问题的



\printbibliography

\end{document}



会报错Undefined control sequence.

**Comment by hushidong** [comment]
正文标注作者加年份的是作者年制的。

**Comment by hushidong** [comment]
![1556196162789](https://user-images.githubusercontent.com/20421795/56736725-75798200-679b-11e9-914f-c7d03a7724e2.jpg)

**Comment by jiewuza** [comment]
哦哦，我这个配置是别的地方copy的😓
刚才搜了一下文档，看到示例中的设置了

不过我发现类似`\authornumcite`这样的命令有个问题，那就是没有复数形式的命令
biblatex中自带的命令比如`\autocite`，都提供了两种格式的用法，即
`\autocite{key1, key2, ...}` 和 `\autocites{key1}{key2}{...}`  （这里省略的可选参数）
我觉得为了遵循这样的规范，是不是应该提供对应的复数形式的命令呢？

**Comment by jiewuza** [comment]
这个文档截图，第一段第一行有textcite的作用，第一段最后一句也是textcite的作用，没有问题吗？

**Comment by hushidong** [comment]
两种编制方式是顺序编码制和作者年制。

复数形式命令也可以给出，主要问题在于要实现什么效果。biblatex的默认效果可能不是咱们需要的，而国标又没有类似的规范性说明，所以即便是提供也只能是尝试性的，因为没有国标支撑。
我看到了你在biblatex那边的提问了，我会尝试给出压缩的复数形式的命令，其它命令则基本按照biblatex的默认样式来。

**Comment by jiewuza** [comment]
哦哦，了解（刚开始使用biblatex，有很多地方都是一知半解）

复数形式主要是为了遵循这样的规范
讲道理不应该写出`\authornumcites{A}{B}{C}`
但是如果这样写了直接报错的话，确实不好

至于规范性方面，我觉得`\authornumcites{A}{B}{C}`应该和`\authornumcite{A,B,C}`类似吧
我测试了一下，结果类似是`作者A[1], 作者B[2], 作者C[3]`

**Comment by hushidong** [comment]
复数形式的命令，和另一种压缩形式[2]-[4]命令已更新。

**Comment by hushidong** [comment]
没有新问题，先关闭啦！
