### ISSUE TITLE
series条目与会议论文卷号的问题

### ISSUE THREAD

**Issue by SXKDZ** [hushidong/biblatex-gb7714-2015#54]
作者您好，非常感谢您的贡献。我在使用过程中遇到了如下两个问题，希望您能抽空解决。谢谢！
（1）
某些期刊还有`series`这一个域，是否最后在`printbibliography`的时候能显示为`RecSys '17: Proceedings of the Eleventh ACM Conference on Recommender Systems`呢？
参考bib如下：
```
@inproceedings{Quadrana:2017gj,
 author = {Quadrana, Massimo and Karatzoglou, Alexandros and Hidasi, Bal\'{a}zs and Cremonesi, Paolo},
 title = {{Personalizing Session-based Recommendations with Hierarchical Recurrent Neural Networks}},
 booktitle = {Proceedings of the Eleventh ACM Conference on Recommender Systems},
 series = {RecSys '17},
 year = {2017},
 isbn = {978-1-4503-4652-8},
 location = {Como, Italy},
 pages = {130--137},
 numpages = {8},
 url = {http://doi.acm.org/10.1145/3109859.3109896},
 doi = {10.1145/3109859.3109896},
 acmid = {3109896},
 publisher = {ACM},
 address = {New York, NY, USA}
} 
```
另外，也有如下bib中包含了`eprint`等与arxiv有关的域，最后显示出来的时候没有空格：
```
@article{Wu:2016wt,
	title         = {{Google's Neural Machine Translation System: Bridging the Gap between Human and Machine Translation}},
	author        = {Wu, Yonghui and Schuster, Mike and Chen, Zhifeng and Le, Quoc V. and Norouzi, Mohammad and Macherey, Wolfgang and Krikun, Maxim and Cao, Yuan and Gao, Qin and Macherey, Klaus and Klingner, Jeff and Shah, Apurva and Johnson, Melvin and Liu, Xiaobing and Gouws, Stephan and Kato, Yoshikiyo and Kudo, Taku and Kazawa, Hideto and Stevens, Keith and Kurian, George and Patil, Nishant and Wang, Wei and Young, Cliff and Smith, Jason and Riesa, Jason and Rudnick, Alex and Vinyals, Oriol and Corrado, Greg and Hughes, Macduff and Dean, Jeffrey},
	year          = 2016,
	month         = sep,
	journal       = {arXiv.org},
	pages         = {1--23},
	url           = {http://arxiv.org/abs/1609.08144v2},
	eprint        = {1609.08144v2},
	eprinttype    = {arxiv},
	eprintclass   = {cs.CL}
}
```
（2）有如下会议论文也有卷号`volume`，打印参考文献时也没有空格：
@inproceedings{Yang:2016ts,
	title         = {{Revisiting Semi-Supervised Learning with Graph Embeddings}},
	author        = {Zhilin Yang and William Cohen and Ruslan Salakhudinov},
	year          = 2016,
	month         = {20--22 Jun},
	booktitle     = {Proceedings of the 33rd International Conference on Machine Learning},
	publisher     = {PMLR},
	address       = {New York, New York, USA},
	series        = {Proceedings of Machine Learning Research},
	volume        = 48,
	pages         = {40--48},
	url           = {http://proceedings.mlr.press/v48/yanga16.html},
	editor        = {Maria Florina Balcan and Kilian Q. Weinberger},
	pdf           = {http://proceedings.mlr.press/v48/yanga16.pdf}
}

（3）最后，我还发现期刊论文没有显示出版社`publisher`域，而会议论文会显示。

**Comment by hushidong** [comment]
对于问题1, series信息到底对应的是什么信息，这在国标中没有明确，如果是跟会议名放一起那么可以直接把他加到会议名中。
如果一定要使用这个域，那么也是可以的，环境是你想把他放哪，能否给个示例？

问题2，国标不要求，eprint，如果一定要用，那么也是可以输出的，关键还是看需求，能否给示例？

问题3 会议论文国标也不要求卷信息，还是那个说法，需求用示例描述一下。

**Comment by SXKDZ** [comment]
感谢回复：
（1）
`QUADRANA M, KARATZOGLOU A, HIDASI B, et al. Personalizing Sessionbased Recommendations with Hierarchical Recurrent Neural Networks[C/OL]//Proceedings of the Eleventh ACM Conference on Recommender Systems. Como, Italy: ACM, 2017: 130137. http://doi.acm.org/10.1145/3109859.3109896. DOI: 10.1145/3109859.3109896.`
这是现在的输出效果。可否输出为：
`QUADRANA M, KARATZOGLOU A, HIDASI B, et al. Personalizing Sessionbased Recommendations with Hierarchical Recurrent Neural Networks[C/OL]//RecSys '17: Proceedings of the Eleventh ACM Conference on Recommender Systems. Como, Italy: ACM, 2017: 130137. http://doi.acm.org/10.1145/3109859.3109896. DOI: 10.1145/3109859.3109896.`
（2）eprint的话，目前已经输出出来了：
`ROWEIS S T, SAUL L K. Nonlinear Dimensionality Reduction by Locally Linear Embedding[J/OL].
Science, 2000, 290(5500): 23232326eprint: https://science.sciencemag.org/content/290/5500/2323.full.pdf. https://science.sciencemag.org/content/290/5500/2323. DOI: 10.1126/science.290.5500.2323.`
只是在eprint之前没有空格，有点丑

（3）会议论文的卷信息目前也是被输出出来了：
`ALMEIDA L B. A Learning Rule for Asynchronous Perceptrons with Feedback in a Combinatorial Environment[C]//Proceedings of the IEEE First International Conference on Neural Networks:vol. 2. San Diego, CA, USA: IEEE Press, 1987: 609618.`
是否可以vol 前加一个空格？

（4）是我不了解  十分抱歉

**Comment by hushidong** [comment]
已更新，见最新。

**Comment by SXKDZ** [comment]
非常感谢！

**Comment by hushidong** [comment]
前述更新，不小心引入了bug，虽然是小细节，见最新的更新。
