### ISSUE TITLE
编译出错，找不到思源宋体字体/urlupdate=gb7714-2015 invalid

### ISSUE THREAD

**Issue by xiaoxuestudent** [hushidong/biblatex-gb7714-2015#55]
开发者您好，我在使用上海交大毕业论文模板时（使用texlive2016，模板版本号0.10.2，https://github.com/sjtug/SJTUThesis/releases/tag/0.10.2 ），出现编译错误说
! Package biblatex Error:  Style 'gb7714-2015' not found
那里的issue说在这儿下载即可。  https://github.com/sjtug/SJTUThesis/issues/191

下载完成后直接双击makefile.bat时编译出错，显示
! fontspec error: "font-not-found"
!
! The font “SourceHanSerifSC-Regular.otf” cannot be found
我在网上找到字体后再入系统再次编译，仍然显示该错误。
如果是用makeall.bat编译，出现的就是
! Package biblatex Error: Option 'urlupdate=gb7714-2015' invalid
See the biblatex package documentation for explanation.
这部我就看不懂了，不知道哪里出错了，可以帮忙查看一下吗？

万分感谢！

**Comment by hushidong** [comment]
字体在这下

https://github.com/adobe-fonts/source-han-serif

另外你也不用全部示例都编译，随便从里头找个小例子，比如不需要思源字体的例子，跑一下就懂了。

**Comment by hushidong** [comment]
可以使用新点的版本的模板。
texlive也可以使用2019.

因为没有texlive环境可以测了，所以你还是使用最新的环境和模板，如果出了问题，我这边也方便跑。

**Comment by xiaoxuestudent** [comment]
试了adobe的字体，还是不行，放弃了texlive2016，改用texlive2019，就没有问题了。我觉得是交大论文的模板可能更新了一些库，因为用texlive2016和2018年的论文模板是没有问题的。现在换用最新的论文模板而不用心的texlive就有这些问题了
感谢，我可以关闭issue了

**Comment by hushidong** [comment]
ok，解决了就好了。
