### ISSUE TITLE
请问一下英文名缩写后怎么加上一个点？

### ISSUE THREAD

**Issue by BiggerHao** [hushidong/biblatex-gb7714-2015#56]
比如Alan Turing，我想显示为`Turing A.`，而非`Turing A`，请问应该怎么修改呢？

**Comment by hushidong** [comment]
才看到，姓名格式的问题，有比较方便的处理方法，就是使用gbnamefmt选项，比如：

```
\documentclass{article}
\usepackage{ctex}
\usepackage{hyperref}
\usepackage[backend=biber,style=gb7714-2015,gbnamefmt=familyahead]{biblatex}


\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{Xue2017DeepLoco,
  title={DeepLoco: dynamic locomotion skills using hierarchical deep reinforcement learning},
  author={Xue, Bin Peng and Berseth, Glen and Yin, Kangkang and Panne, Michiel Van De},
  journal={Acm Transactions on Graphics},
  volume={36},
  number={4},
  pages={1-13},
  year={2017},
}

@article{Zhang2015Towards,
  title={Towards Vision-Based Deep Reinforcement Learning for Robotic Motion Control},
  author={Zhang, Fang Yi and Leitner, Juergen and Milford, Michael and Upcroft, Ben and Corke, Peter},
  journal={Computer Science},
  year={2015},
}

\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}

\nocite{*}

\printbibliography

\end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/69490027-43a8d500-0ebc-11ea-8c60-8f8c63379a77.png)


这是比较快速的方法，你可以仔细看一下biblatex-gb7714-2015.PDF文档，如果选项不能满足要求，那么只能去修改处理姓名的宏了。比如：
```
\newbibmacro*{name:gbuppercase}
```
等，可以根据需要改成你要求的格式。

**Comment by BiggerHao** [comment]
@hushidong 谢谢，我用这个选项成功解决了我的问题。我之前看到了gbnamefmt这个选项的设置，没想到各个选项之间还有这么细微的差异，建议在文档里稍加一个具体的例子，会更清晰一些。

**Comment by hushidong** [comment]
这个选项的几个情况是最常用的几个情况，西文的3个，中文要求的2个。

在选项的说明中的确可以给出示例来，感谢建议。

**Comment by BiggerHao** [comment]
我再做一点补充。一开始没注意到加上`gbnamefmt=familyahead`之后，作者姓后面也有一个逗号，比如`Turing, A.`，与我想要的效果不一致。参考了[这里](https://tex.stackexchange.com/questions/17583/biblatex-remove-commas-between-last-and-first-names-in-bibliography)以后，在preamble里加上了`\renewcommand*{\revsdnamepunct}{}`就能去除这个逗号了。

**Comment by hushidong** [comment]
对的，就是这样处理。
