### ISSUE TITLE
[doc] 页面标尺可能遮挡文字，建议去除

### ISSUE THREAD

**Issue by muzimuzhi** [hushidong/biblatex-gb7714-2015#74]
遮挡（末行）文字的例子
![image](https://user-images.githubusercontent.com/6376638/82286263-e6579180-99cf-11ea-8247-796957fcf7ed.png)

相关源码
https://github.com/hushidong/biblatex-gb7714-2015/blob/7bfd30984a6070b7856bc84897034a0c37ba13b3/biblatex-gb7714-2015-preamble.tex#L38-L42

**Comment by muzimuzhi** [comment]
该标尺由 https://github.com/hushidong/biblatex-gb7714-2015/commit/cdb722df8f9763a949577c619ef8b89f156686b5 引入，之后的 https://github.com/hushidong/biblatex-gb7714-2015/commit/f6738892ee5724667eee67fc9f4922e00b6eca49 修改了标尺线条的颜色和间隔。

**Comment by hushidong** [comment]
好的，我都快忘了测试什么东西的时候加进来的了，没有什么特别的意义，下次更新再去掉吧。

**Comment by muzimuzhi** [comment]
请问是本地已经修改，尚未推送到远程吗？我看 github 上的相关文件并未修改

**Comment by hushidong** [comment]
又看了下，应该早就去掉了，原来是在页眉页脚里加的，已注释掉。

**Comment by muzimuzhi** [comment]
找到了。提交 https://github.com/hushidong/biblatex-gb7714-2015/commit/263e6daad7d731f7c8b768694426e2d63dde5d8e (Jul 4, 2020) 注释了绘制页面标尺的代码。之前我只看到 `fgruler` 宏包加载和设置的代码没有移除，抱歉。
