### ISSUE TITLE
连续出版物的析出文献中日期前符号的问题

### ISSUE THREAD

**Issue by l460289052** [hushidong/biblatex-gb7714-2015#75]
使用的是上交的模板，模板中项目的版本为`2020/03/20 v1.0u`
例如对于连续出版物
```
@inproceedings{
Eagle,
    title={Eagle: User profile-based anomaly detection for securing Hadoop clusters},
    author={Gupta, Chaitali and Sinha, Ranjan and Zhang, Yong},
    booktitle={2015 IEEE International Conference on Big Data (Big Data)},
    pages={1336--1343},
    year={2015}
}
```
生成的参考文献为`GUPTA C, SINHA R, ZHANG Y. Eagle: User profile-based anomaly detection for secur-ing Hadoop clusters[C]. 2015 IEEE International Conference on Big Data (Big Data). 2015:1336-1343.`。
但7714-2015中连续出版物的格式为
```
析出文献主要责任者.析出文献题名[文献类型标识/文献载体标识].连续出版物题名:其他题名信息,年,卷(期):页码[引用日期].获取和访问路径.数字对象唯一标识符.
```
在年前面用的是逗号`,`而不是点`.`。因为是新入门latex，所以请求大佬抽时间修复或尽快告知如何修改

**Comment by hushidong** [comment]
inproceedings
属于专著析出的文献。格式与article是不同的，如果加上出版信息，年份前是逗号，如果没有的话，前面是booktitle那么应用点。

**Comment by hushidong** [comment]
论文集和会议录格式与专著类似，从中析出文献与专著析出文献类似。

**Comment by hushidong** [comment]
http://cci.drexel.edu/bigdata/bigdata2015/index.html

看看是不是这个，信息补全就没有疑问了。

**Comment by hushidong** [comment]
找到了在这
Wei Yi Liu, Morris H. Hsiao, and Shih Yao Dai, DNA Analysis with MapReduce

Chaitali Gupta, Ranjan Sinha, and Yong Zhang, Eagle: User Profile-based Anomaly Detection in Hadoop Clusters

Manuel Diaz-Granados, Javier Diaz-Montes, and Manish Parashar, Investigating Insurance Fraud using Social Media

**Comment by l460289052** [comment]
非常感谢，
抱歉我因为我个人的错误打扰您了

**Comment by hushidong** [comment]
客气
