### ISSUE TITLE
同一处引用两篇文献时需要压缩序号

### ISSUE THREAD

**Issue by zepinglee** [hushidong/biblatex-gb7714-2015#78]
目前的实现是，三篇以上连续的文献编号会压缩，使用“-”连接。

标准第 10.1.2 节：
<img width="723" alt="Screen Shot 2020-06-29 at 00 48 40" src="https://user-images.githubusercontent.com/12290822/85953423-ac03eb80-b9a2-11ea-9936-1fb9e1f0eae4.png">
注意到这里的引用的编号是“[255-256]”，也就是连续的两篇文献就要压缩。

**Comment by hushidong** [comment]
这个压缩其他地方没有明确说明，是3个开始压缩，还是2个开始压缩么？

我一直认为传统的三个开始压缩的，所以一直都没有注意到这个问题。

功能倒是都实现了的，我以前看你的ustc的实现是两个压缩，所以就做了处理，但这段代码一直没启用，现在是放在readme的问题中。我看看后面大家的需求，然后加上去吧。

**Comment by zepinglee** [comment]
这里“如遇连续序号，起讫序号间用短横线连接”可以理解为，只要连续就压缩，所以其实 `gbt7714-bibtex-style` 实现的就是 2 个开始压缩，所以这部分应该设为默认。

THU 和 USTC 的写作指南给出的示例中都有 2 个压缩的例子，其中 USTC 的通过错误示例强调了 2 个必须压缩。

**Comment by hushidong** [comment]
好的，我有空把代码加进去。

**Comment by hushidong** [comment]
https://github.com/hushidong/biblatex-gb7714-2015/commit/263e6daad7d731f7c8b768694426e2d63dde5d8e
