### ISSUE TITLE
\mkrelatedstring will be deprecated in favour of \mkrelatedstringtext

### ISSUE THREAD

**Issue by moewew** [hushidong/biblatex-gb7714-2015#80]
Apologies for writing in English.

Due to https://github.com/plk/biblatex/issues/1057 (and in particular https://github.com/plk/biblatex/commit/f5a096a6395e274b3af9d01d5fb4aecddeff138d) we are planning to deprecate `\mkrelatedstring` in favour of the new command `\mkrelatedstringtext`.

This style uses `\mkrelatedstring` in https://github.com/hushidong/biblatex-gb7714-2015/blob/master/gb7714-2015.bbx and https://github.com/hushidong/biblatex-gb7714-2015/blob/master/gb7714-2015ay.bbx.

In order to avoid deprecation warnings it is recommended to switch over to the new command.

This could for example be done by using `\mkrelatedstringtext` and adding the following fallback definition 
```latex
\providecommand*{\mkrelatedstringtext}[1]{{{\mainlang #1}}}
```

**Comment by hushidong** [comment]
ok，thank you, I will cope with it soon.

**Comment by hushidong** [comment]
because the code clip with `\mkrelatedstring` is used to deal compatability with biblatex v3.8-3.9， for the newer biblatex version this command is not explicitly used，so it is not need to change the command. thanks again！
