### ISSUE TITLE
参考文献作者年失败

### ISSUE THREAD

**Issue by wuming365** [hushidong/biblatex-gb7714-2015#82]
一个非常简单但却令人头疼的问题……
我使用VS code进行latex开题报告模板的编译，在参考文献处想要使用作者年格式，但是总是出现编号格式。编译模式如下图
![image](https://user-images.githubusercontent.com/34066985/104955109-97ea0f00-5a04-11eb-83c9-119eb706825c.png)

以下为代码片段：
![image](https://user-images.githubusercontent.com/34066985/104954840-0bd7e780-5a04-11eb-911d-29aa5779c695.png)
![image](https://user-images.githubusercontent.com/34066985/104954900-2b6f1000-5a04-11eb-9752-cb712f1e885c.png)
![image](https://user-images.githubusercontent.com/34066985/104955109-97ea0f00-5a04-11eb-83c9-119eb706825c.png)
如上图代码设置自检是没有问题的，但是结果总是不对，我因此修改authoryear处为numbers、super等等，但结果并不会因此发生任何变化，以下为统一的结果输出：

这是citep的结果
![image](https://user-images.githubusercontent.com/34066985/104955222-d5e73300-5a04-11eb-906e-5e1a4f34108e.png)
这是citet的结果
![image](https://user-images.githubusercontent.com/34066985/104955160-b5b77400-5a04-11eb-99b2-2e70de558b8a.png)
参考文献附录为：
![image](https://user-images.githubusercontent.com/34066985/104955265-e5667c00-5a04-11eb-966b-d944d6d4d88e.png)
并不是我想要的，但我搜寻了所有可以搜寻的方式，并未找到合理的解决方案，因此我下载了编译模板使用说明的代码直接进行编译，但结果出现了和之前一样的错误，如图
![image](https://user-images.githubusercontent.com/34066985/104955395-2c547180-5a05-11eb-867b-405c706dd3dd.png)

到这里为止我已经自己无法解决，因此向师兄求助，万分感谢！

**Comment by hushidong** [comment]
最近我看不到github上的图了，发我邮箱吧，最好给个实例，把你的敏感信息去掉就，能反应问题就行。

**Comment by zepinglee** [comment]
这个用的是 ucasthesis 把？模板是用 bibtex 编译的，跟 biblatex 无关

**Comment by hushidong** [comment]
嗯，主要是环境问题，已经解决。
