### ISSUE TITLE
关于“5. Examples/著录和标注结果示例”中两个重要示例只有图片没有实现代码

### ISSUE THREAD

**Issue by TigerZhao007** [hushidong/biblatex-gb7714-2015#83]
首先感谢作者！
readme中的“5. Examples/著录和标注结果示例”部分，2个非常实用的模板，但是好像只有图片？可以作为初学者的模板。

**Comment by hushidong** [comment]
代码都是有的，见根目录下的几个文件夹，下面有大量的示例，都可以看一下。

我在readme里添加了部分的相关代码链接，包括了标注的，国标文档复现的，还有名字格式的。

但，其实更多的示例可以去看biblatex-gb7714-2015.pdf，里面的所有图片都是由同名的例子生成的，每个图片的名字可以从biblatex-gb7714-2015.tex中查看。
