### ISSUE TITLE
请问有无支持 gbt7714-2005 的打算？

### ISSUE THREAD

**Issue by tanukihee** [hushidong/biblatex-gb7714-2015#85]
虽然有 https://github.com/li-zhiqi/biblatex-gb 与 https://github.com/szsdk/biblatex-gbt77142005 ，但已经很久没有更新了

**Comment by hushidong** [comment]
你好，不知道你有没有看过标准文档本身。我初步的研究结果是，两者没有什么本质的差别，一般用户直接用2015就可以了。
见：https://github.com/TheNetAdmin/zjuthesis/issues/23

当然，如果你有什么发现，或者有什么需求都可以提出来，即便是需要改动，也是非常少的。

顺便说一下，其实开发biblatex-gb7714-2015完全是因为李志奇（https://github.com/li-zhiqi/biblatex-gb ）当年不更新了，所以就再做一个吧，当然从问世到现在也过去一些年了。

**Comment by tanukihee** [comment]
谢谢！
