### ISSUE TITLE
能否在 bibstyle 的顺序编码制下增加选项，使得年份可以提前到作者后方？

### ISSUE THREAD

**Issue by tanukihee** [hushidong/biblatex-gb7714-2015#90]
由 https://github.com/whutug/whu-thesis/issues/53#issuecomment-817084663 与 https://github.com/stone-zeng/fduthesis/issues/183#issuecomment-793537978 而来

期望效果与 bibtex 的 `year.after.author` 效果相同

**Comment by hushidong** [comment]
这个问题目前是用，printbibliograhpy[env=numerical] 方式解决的。这样样式定义也不用标注和著录分开了。如果要使用的话要更新一下biblatex-gb7714-2015

比如：
```

\documentclass[twoside]{article}
    \usepackage{ctex}
    \usepackage{fontspec}
\usepackage[backend=biber,style=gb7714-2015ay]{biblatex}
%\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{anon1981-628,
  title   = {Coffee drinking and cancer of the pancreas},
  journal = {Br Med J},
  year    = {1981},
  volume  = {283},
  number  = {6292},
  pages   = {628}
}

@ARTICLE{Rgsfda2008--,
  author       = {{Research Group of Shanghai Food and Drug Administration}},
  title        = {A study on online pharmaceutical operating situation and supervision mechanism},
  Journaltitle = {Shanghai food and drug information research},
  DATE         = {2008},
  number       = {1},
  pages        = {8-11},
}

@ARTICLE{关立哲2014--,
  author       = {关立哲 and 韩纪富 and 张晨延},
  title        = {科技期刊编辑审读中要注重比较思维的科学运用},
  Journaltitle = {编辑学报},
  DATE         = {2014},
  VOLUME       = {26},
  number       = {2},
  pages        = {144-146}
}

@ARTICLE{熊平2005--,
  author       = {熊平 and 吴颉},
  title        = {从交易费用的角度谈如何构建药品流通的良性机制},
  Journaltitle = {中国物价},
  DATE         = {2005},
  number       = {8},
  pages        = {42-45},
}

\end{filecontents}

\addbibresource{\jobname.bib}

    \begin{document}

\nocite{*}

\printbibliography[env=numerical]
%\printbibliography


    \end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/114292960-e61f2380-9ac4-11eb-8bbc-21cbcfb3ee74.png)

**Comment by hushidong** [comment]
这个numerical环境其实应该用numeric的，当时定义的时候写错了，将错就错吧。

**Comment by tanukihee** [comment]
谢谢！

**Comment by hushidong** [comment]
上述解决方案，可能不是非常完美，所以在新版本中将取出这种用法，而用gbalign选项来控制。

gbalign =right，left，center，gb7714-2015，gb7714-2015ay. default: right for numeric
style and gb7714-2015ay for author-year style
为控制文献表数字序号标签增加的选项，用于选择是否生成序号标签及其对齐方式。
• gbalign=right，数字序号标签，是 list 环境中的标签右对齐，是 gb7714-2015
样式的默认选项；
• gbalign=left，数字序号标签，是 list 环境中的标签左对齐；
• gbalign=center，数字序号标签，是 list 环境中的等宽标签，数字在 [] 内居中；
• gbalign=gb7714-2015，数字序号标签，是项对齐方式，即段落环境中标签使
用原始宽度，标签与条目内容等间距。
• gbalign=gb7714-2015ay，无数字序号标签，是 author-year 风格的文献表，是
gb7714-2015ay 样式的默认选项。

所以biblatex-gb7714-2015v1.0x版本用前面给出方式，后面的版本需要设置gbalign=right或left或center都可以。

**Comment by hushidong** [comment]
见 https://github.com/hushidong/biblatex-gb7714-2015/commit/3011192ebe22618f65be8553fbe9b304cdf4cc86
