### ISSUE TITLE
关于参考文献的悬挂缩进

### ISSUE THREAD

**Issue by ephemer1s** [hushidong/biblatex-gb7714-2015#93]
正常GB/T7714-2015格式的确是有悬挂缩进的。但我校北京理工大学对于本科毕设参考文献的要求是无悬挂缩进。想请问在该要求下我应如何修改我的格式？

**Comment by hushidong** [comment]
你自己研究的话，可以看一下文档中的gbalign选项，以及关于段落格式调整的说明。

如果需要帮助实现，可以给个例子，放上来，一看就明了的。

**Comment by hushidong** [comment]
可以参考一下

https://github.com/hushidong/biblatex-gb7714-2015/issues/62
