### ISSUE TITLE
使用 biber 编译出现错误 “I found no \citation commands”

### ISSUE THREAD

**Issue by 19PDP** [hushidong/biblatex-gb7714-2015#94]
当指定 `backend=biber` 时编译出现错误：
```bash
This is BibTeX, Version 0.99d (TeX Live 2021)
The top-level auxiliary file: test.aux
I found no \citation commands---while reading file test.aux
I found no \bibdata command---while reading file test.aux
I found no \bibstyle command---while reading file test.aux
(There were 3 error messages)
出现错误
```
排版效果如下图，且无法打印文献列表。
![biber 编译效果](https://i.loli.net/2021/05/24/J8rUmuWOSzGP7Ca.png)

<br>

更改选项为 `backend=bibtex` 后成功编译，且显示正常。

<br>

最小实例：
```latex
\documentclass{article}%文档类%导言区开始:

\usepackage{ctex}%加载ctex宏包，中文支持
\usepackage{geometry}%加载geometry宏包，定义版面
\usepackage[colorlinks=true,pdfstartview=FitH,%
linkcolor=blue,anchorcolor=violet,citecolor=magenta]{hyperref}%加载hyperref宏包，使用超链接

% 问题所在，使用 biber 编译出现错误
\usepackage[backend=biber,bibstyle=gb7714-2015,%nature,%%加载biblatex宏包，使用参考文献
citestyle=gb7714-2015%,backref=true%%其中后端backend使用biber
]{biblatex}%标注(引用)样式citestyle，著录样式bibstyle都采用gb7714-2015样式

% 使用 bibtex 可以正常编译
%\usepackage[backend=bibtex,bibstyle=gb7714-2015,
%citestyle=gb7714-2015]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{egbibdata.bib}
	@Book{Peebles2001-100-100,
		Title                    = {Probability, random variable, and random signal Principles and \LaTeX{}},
		Address                  = {New York},
		Author                   = {von Peebles, Jr., P. Z.},
		Edition                  = {4},
		Pages                    = {100},
		Publisher                = {McGraw-Hill},
		Year                     = {2001}
	}
\end{filecontents}

\addbibresource[location=local]{egbibdata.bib}%biblatex宏包的参考文献数据源加载方式

\begin{document}%正文区开始:
	
	%正文内容，引用参考文献
	
	1. 不带页码的引用(顺序编码制上标，方括号包围；作者年制行内，括号包围):\\
	见文献\cite{Peebles2001-100-100}\\
	见文献\upcite{Peebles2001-100-100}\\
	见文献\supercite{Peebles2001-100-100}

	%打印参考文献表
	\printbibliography[heading=bibliography,title=参考文献]
\end{document}
```

**Comment by hushidong** [comment]
你说是用biber编译，但你的显示是

This is BibTeX, Version 0.99d (TeX Live 2021)
The top-level auxiliary file: test.aux
I found no \citation commands---while reading file test.aux
I found no \bibdata command---while reading file test.aux
I found no \bibstyle command---while reading file test.aux
(There were 3 error messages)
出现错误
其实是用bibtex编译的。

所以换backend就对了。

当然这么用也是没太大问题的，只是对于中文来说可能无法得到想要的效果。

所以还是要正确的用biber编译。

**Comment by 19PDP** [comment]
> 你说是用biber编译，但你的显示是
> 
> This is BibTeX, Version 0.99d (TeX Live 2021)
> The top-level auxiliary file: test.aux
> I found no \citation commands---while reading file test.aux
> I found no \bibdata command---while reading file test.aux
> I found no \bibstyle command---while reading file test.aux
> (There were 3 error messages)
> 出现错误
> 其实是用bibtex编译的。
> 
> 所以换backend就对了。
> 
> 当然这么用也是没太大问题的，只是对于中文来说可能无法得到想要的效果。
> 
> 所以还是要正确的用biber编译。

多谢您的回答，是我搞错了。非常感谢
